//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	v1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	configsync "kpt.dev/configsync/pkg/api/configsync"
	v1beta1 "kpt.dev/configsync/pkg/api/configsync/v1beta1"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*ConfigSyncError)(nil), (*v1beta1.ConfigSyncError)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ConfigSyncError_To_v1beta1_ConfigSyncError(a.(*ConfigSyncError), b.(*v1beta1.ConfigSyncError), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ConfigSyncError)(nil), (*ConfigSyncError)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ConfigSyncError_To_v1alpha1_ConfigSyncError(a.(*v1beta1.ConfigSyncError), b.(*ConfigSyncError), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ContainerLogLevelOverride)(nil), (*v1beta1.ContainerLogLevelOverride)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ContainerLogLevelOverride_To_v1beta1_ContainerLogLevelOverride(a.(*ContainerLogLevelOverride), b.(*v1beta1.ContainerLogLevelOverride), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ContainerLogLevelOverride)(nil), (*ContainerLogLevelOverride)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ContainerLogLevelOverride_To_v1alpha1_ContainerLogLevelOverride(a.(*v1beta1.ContainerLogLevelOverride), b.(*ContainerLogLevelOverride), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ContainerResourcesSpec)(nil), (*v1beta1.ContainerResourcesSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ContainerResourcesSpec_To_v1beta1_ContainerResourcesSpec(a.(*ContainerResourcesSpec), b.(*v1beta1.ContainerResourcesSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ContainerResourcesSpec)(nil), (*ContainerResourcesSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ContainerResourcesSpec_To_v1alpha1_ContainerResourcesSpec(a.(*v1beta1.ContainerResourcesSpec), b.(*ContainerResourcesSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ErrorSummary)(nil), (*v1beta1.ErrorSummary)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ErrorSummary_To_v1beta1_ErrorSummary(a.(*ErrorSummary), b.(*v1beta1.ErrorSummary), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ErrorSummary)(nil), (*ErrorSummary)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ErrorSummary_To_v1alpha1_ErrorSummary(a.(*v1beta1.ErrorSummary), b.(*ErrorSummary), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Git)(nil), (*v1beta1.Git)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Git_To_v1beta1_Git(a.(*Git), b.(*v1beta1.Git), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.Git)(nil), (*Git)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Git_To_v1alpha1_Git(a.(*v1beta1.Git), b.(*Git), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GitStatus)(nil), (*v1beta1.GitStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_GitStatus_To_v1beta1_GitStatus(a.(*GitStatus), b.(*v1beta1.GitStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.GitStatus)(nil), (*GitStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_GitStatus_To_v1alpha1_GitStatus(a.(*v1beta1.GitStatus), b.(*GitStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HelmBase)(nil), (*v1beta1.HelmBase)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_HelmBase_To_v1beta1_HelmBase(a.(*HelmBase), b.(*v1beta1.HelmBase), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HelmRepoSync)(nil), (*v1beta1.HelmRepoSync)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_HelmRepoSync_To_v1beta1_HelmRepoSync(a.(*HelmRepoSync), b.(*v1beta1.HelmRepoSync), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.HelmRepoSync)(nil), (*HelmRepoSync)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_HelmRepoSync_To_v1alpha1_HelmRepoSync(a.(*v1beta1.HelmRepoSync), b.(*HelmRepoSync), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HelmRootSync)(nil), (*v1beta1.HelmRootSync)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_HelmRootSync_To_v1beta1_HelmRootSync(a.(*HelmRootSync), b.(*v1beta1.HelmRootSync), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HelmStatus)(nil), (*v1beta1.HelmStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_HelmStatus_To_v1beta1_HelmStatus(a.(*HelmStatus), b.(*v1beta1.HelmStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.HelmStatus)(nil), (*HelmStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_HelmStatus_To_v1alpha1_HelmStatus(a.(*v1beta1.HelmStatus), b.(*HelmStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Oci)(nil), (*v1beta1.Oci)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Oci_To_v1beta1_Oci(a.(*Oci), b.(*v1beta1.Oci), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.Oci)(nil), (*Oci)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Oci_To_v1alpha1_Oci(a.(*v1beta1.Oci), b.(*Oci), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OciStatus)(nil), (*v1beta1.OciStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_OciStatus_To_v1beta1_OciStatus(a.(*OciStatus), b.(*v1beta1.OciStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.OciStatus)(nil), (*OciStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OciStatus_To_v1alpha1_OciStatus(a.(*v1beta1.OciStatus), b.(*OciStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OverrideSpec)(nil), (*v1beta1.OverrideSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_OverrideSpec_To_v1beta1_OverrideSpec(a.(*OverrideSpec), b.(*v1beta1.OverrideSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.OverrideSpec)(nil), (*OverrideSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OverrideSpec_To_v1alpha1_OverrideSpec(a.(*v1beta1.OverrideSpec), b.(*OverrideSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RenderingStatus)(nil), (*v1beta1.RenderingStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RenderingStatus_To_v1beta1_RenderingStatus(a.(*RenderingStatus), b.(*v1beta1.RenderingStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.RenderingStatus)(nil), (*RenderingStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RenderingStatus_To_v1alpha1_RenderingStatus(a.(*v1beta1.RenderingStatus), b.(*RenderingStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RepoSync)(nil), (*v1beta1.RepoSync)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RepoSync_To_v1beta1_RepoSync(a.(*RepoSync), b.(*v1beta1.RepoSync), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.RepoSync)(nil), (*RepoSync)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RepoSync_To_v1alpha1_RepoSync(a.(*v1beta1.RepoSync), b.(*RepoSync), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RepoSyncCondition)(nil), (*v1beta1.RepoSyncCondition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RepoSyncCondition_To_v1beta1_RepoSyncCondition(a.(*RepoSyncCondition), b.(*v1beta1.RepoSyncCondition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.RepoSyncCondition)(nil), (*RepoSyncCondition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RepoSyncCondition_To_v1alpha1_RepoSyncCondition(a.(*v1beta1.RepoSyncCondition), b.(*RepoSyncCondition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RepoSyncList)(nil), (*v1beta1.RepoSyncList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RepoSyncList_To_v1beta1_RepoSyncList(a.(*RepoSyncList), b.(*v1beta1.RepoSyncList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.RepoSyncList)(nil), (*RepoSyncList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RepoSyncList_To_v1alpha1_RepoSyncList(a.(*v1beta1.RepoSyncList), b.(*RepoSyncList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RepoSyncOverrideSpec)(nil), (*v1beta1.RepoSyncOverrideSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RepoSyncOverrideSpec_To_v1beta1_RepoSyncOverrideSpec(a.(*RepoSyncOverrideSpec), b.(*v1beta1.RepoSyncOverrideSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.RepoSyncOverrideSpec)(nil), (*RepoSyncOverrideSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RepoSyncOverrideSpec_To_v1alpha1_RepoSyncOverrideSpec(a.(*v1beta1.RepoSyncOverrideSpec), b.(*RepoSyncOverrideSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RepoSyncSpec)(nil), (*v1beta1.RepoSyncSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RepoSyncSpec_To_v1beta1_RepoSyncSpec(a.(*RepoSyncSpec), b.(*v1beta1.RepoSyncSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.RepoSyncSpec)(nil), (*RepoSyncSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RepoSyncSpec_To_v1alpha1_RepoSyncSpec(a.(*v1beta1.RepoSyncSpec), b.(*RepoSyncSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RepoSyncStatus)(nil), (*v1beta1.RepoSyncStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RepoSyncStatus_To_v1beta1_RepoSyncStatus(a.(*RepoSyncStatus), b.(*v1beta1.RepoSyncStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.RepoSyncStatus)(nil), (*RepoSyncStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RepoSyncStatus_To_v1alpha1_RepoSyncStatus(a.(*v1beta1.RepoSyncStatus), b.(*RepoSyncStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ResourceRef)(nil), (*v1beta1.ResourceRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ResourceRef_To_v1beta1_ResourceRef(a.(*ResourceRef), b.(*v1beta1.ResourceRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ResourceRef)(nil), (*ResourceRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ResourceRef_To_v1alpha1_ResourceRef(a.(*v1beta1.ResourceRef), b.(*ResourceRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RootSync)(nil), (*v1beta1.RootSync)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RootSync_To_v1beta1_RootSync(a.(*RootSync), b.(*v1beta1.RootSync), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.RootSync)(nil), (*RootSync)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RootSync_To_v1alpha1_RootSync(a.(*v1beta1.RootSync), b.(*RootSync), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RootSyncCondition)(nil), (*v1beta1.RootSyncCondition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RootSyncCondition_To_v1beta1_RootSyncCondition(a.(*RootSyncCondition), b.(*v1beta1.RootSyncCondition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.RootSyncCondition)(nil), (*RootSyncCondition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RootSyncCondition_To_v1alpha1_RootSyncCondition(a.(*v1beta1.RootSyncCondition), b.(*RootSyncCondition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RootSyncList)(nil), (*v1beta1.RootSyncList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RootSyncList_To_v1beta1_RootSyncList(a.(*RootSyncList), b.(*v1beta1.RootSyncList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.RootSyncList)(nil), (*RootSyncList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RootSyncList_To_v1alpha1_RootSyncList(a.(*v1beta1.RootSyncList), b.(*RootSyncList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RootSyncOverrideSpec)(nil), (*v1beta1.RootSyncOverrideSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RootSyncOverrideSpec_To_v1beta1_RootSyncOverrideSpec(a.(*RootSyncOverrideSpec), b.(*v1beta1.RootSyncOverrideSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.RootSyncOverrideSpec)(nil), (*RootSyncOverrideSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RootSyncOverrideSpec_To_v1alpha1_RootSyncOverrideSpec(a.(*v1beta1.RootSyncOverrideSpec), b.(*RootSyncOverrideSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RootSyncRoleRef)(nil), (*v1beta1.RootSyncRoleRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RootSyncRoleRef_To_v1beta1_RootSyncRoleRef(a.(*RootSyncRoleRef), b.(*v1beta1.RootSyncRoleRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.RootSyncRoleRef)(nil), (*RootSyncRoleRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RootSyncRoleRef_To_v1alpha1_RootSyncRoleRef(a.(*v1beta1.RootSyncRoleRef), b.(*RootSyncRoleRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RootSyncSpec)(nil), (*v1beta1.RootSyncSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RootSyncSpec_To_v1beta1_RootSyncSpec(a.(*RootSyncSpec), b.(*v1beta1.RootSyncSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.RootSyncSpec)(nil), (*RootSyncSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RootSyncSpec_To_v1alpha1_RootSyncSpec(a.(*v1beta1.RootSyncSpec), b.(*RootSyncSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RootSyncStatus)(nil), (*v1beta1.RootSyncStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RootSyncStatus_To_v1beta1_RootSyncStatus(a.(*RootSyncStatus), b.(*v1beta1.RootSyncStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.RootSyncStatus)(nil), (*RootSyncStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RootSyncStatus_To_v1alpha1_RootSyncStatus(a.(*v1beta1.RootSyncStatus), b.(*RootSyncStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SecretReference)(nil), (*v1beta1.SecretReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SecretReference_To_v1beta1_SecretReference(a.(*SecretReference), b.(*v1beta1.SecretReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.SecretReference)(nil), (*SecretReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_SecretReference_To_v1alpha1_SecretReference(a.(*v1beta1.SecretReference), b.(*SecretReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SourceStatus)(nil), (*v1beta1.SourceStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SourceStatus_To_v1beta1_SourceStatus(a.(*SourceStatus), b.(*v1beta1.SourceStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.SourceStatus)(nil), (*SourceStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_SourceStatus_To_v1alpha1_SourceStatus(a.(*v1beta1.SourceStatus), b.(*SourceStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Status)(nil), (*v1beta1.Status)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Status_To_v1beta1_Status(a.(*Status), b.(*v1beta1.Status), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.Status)(nil), (*Status)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Status_To_v1alpha1_Status(a.(*v1beta1.Status), b.(*Status), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SyncStatus)(nil), (*v1beta1.SyncStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SyncStatus_To_v1beta1_SyncStatus(a.(*SyncStatus), b.(*v1beta1.SyncStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.SyncStatus)(nil), (*SyncStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_SyncStatus_To_v1alpha1_SyncStatus(a.(*v1beta1.SyncStatus), b.(*SyncStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ValuesFileRef)(nil), (*v1beta1.ValuesFileRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ValuesFileRef_To_v1beta1_ValuesFileRef(a.(*ValuesFileRef), b.(*v1beta1.ValuesFileRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ValuesFileRef)(nil), (*ValuesFileRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ValuesFileRef_To_v1alpha1_ValuesFileRef(a.(*v1beta1.ValuesFileRef), b.(*ValuesFileRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta1.HelmBase)(nil), (*HelmBase)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_HelmBase_To_v1alpha1_HelmBase(a.(*v1beta1.HelmBase), b.(*HelmBase), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta1.HelmRootSync)(nil), (*HelmRootSync)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_HelmRootSync_To_v1alpha1_HelmRootSync(a.(*v1beta1.HelmRootSync), b.(*HelmRootSync), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_ConfigSyncError_To_v1beta1_ConfigSyncError(in *ConfigSyncError, out *v1beta1.ConfigSyncError, s conversion.Scope) error {
	out.Code = in.Code
	out.ErrorMessage = in.ErrorMessage
	out.Resources = *(*[]v1beta1.ResourceRef)(unsafe.Pointer(&in.Resources))
	return nil
}

// Convert_v1alpha1_ConfigSyncError_To_v1beta1_ConfigSyncError is an autogenerated conversion function.
func Convert_v1alpha1_ConfigSyncError_To_v1beta1_ConfigSyncError(in *ConfigSyncError, out *v1beta1.ConfigSyncError, s conversion.Scope) error {
	return autoConvert_v1alpha1_ConfigSyncError_To_v1beta1_ConfigSyncError(in, out, s)
}

func autoConvert_v1beta1_ConfigSyncError_To_v1alpha1_ConfigSyncError(in *v1beta1.ConfigSyncError, out *ConfigSyncError, s conversion.Scope) error {
	out.Code = in.Code
	out.ErrorMessage = in.ErrorMessage
	out.Resources = *(*[]ResourceRef)(unsafe.Pointer(&in.Resources))
	return nil
}

// Convert_v1beta1_ConfigSyncError_To_v1alpha1_ConfigSyncError is an autogenerated conversion function.
func Convert_v1beta1_ConfigSyncError_To_v1alpha1_ConfigSyncError(in *v1beta1.ConfigSyncError, out *ConfigSyncError, s conversion.Scope) error {
	return autoConvert_v1beta1_ConfigSyncError_To_v1alpha1_ConfigSyncError(in, out, s)
}

func autoConvert_v1alpha1_ContainerLogLevelOverride_To_v1beta1_ContainerLogLevelOverride(in *ContainerLogLevelOverride, out *v1beta1.ContainerLogLevelOverride, s conversion.Scope) error {
	out.ContainerName = in.ContainerName
	out.LogLevel = in.LogLevel
	return nil
}

// Convert_v1alpha1_ContainerLogLevelOverride_To_v1beta1_ContainerLogLevelOverride is an autogenerated conversion function.
func Convert_v1alpha1_ContainerLogLevelOverride_To_v1beta1_ContainerLogLevelOverride(in *ContainerLogLevelOverride, out *v1beta1.ContainerLogLevelOverride, s conversion.Scope) error {
	return autoConvert_v1alpha1_ContainerLogLevelOverride_To_v1beta1_ContainerLogLevelOverride(in, out, s)
}

func autoConvert_v1beta1_ContainerLogLevelOverride_To_v1alpha1_ContainerLogLevelOverride(in *v1beta1.ContainerLogLevelOverride, out *ContainerLogLevelOverride, s conversion.Scope) error {
	out.ContainerName = in.ContainerName
	out.LogLevel = in.LogLevel
	return nil
}

// Convert_v1beta1_ContainerLogLevelOverride_To_v1alpha1_ContainerLogLevelOverride is an autogenerated conversion function.
func Convert_v1beta1_ContainerLogLevelOverride_To_v1alpha1_ContainerLogLevelOverride(in *v1beta1.ContainerLogLevelOverride, out *ContainerLogLevelOverride, s conversion.Scope) error {
	return autoConvert_v1beta1_ContainerLogLevelOverride_To_v1alpha1_ContainerLogLevelOverride(in, out, s)
}

func autoConvert_v1alpha1_ContainerResourcesSpec_To_v1beta1_ContainerResourcesSpec(in *ContainerResourcesSpec, out *v1beta1.ContainerResourcesSpec, s conversion.Scope) error {
	out.ContainerName = in.ContainerName
	out.CPURequest = in.CPURequest
	out.MemoryRequest = in.MemoryRequest
	out.CPULimit = in.CPULimit
	out.MemoryLimit = in.MemoryLimit
	return nil
}

// Convert_v1alpha1_ContainerResourcesSpec_To_v1beta1_ContainerResourcesSpec is an autogenerated conversion function.
func Convert_v1alpha1_ContainerResourcesSpec_To_v1beta1_ContainerResourcesSpec(in *ContainerResourcesSpec, out *v1beta1.ContainerResourcesSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ContainerResourcesSpec_To_v1beta1_ContainerResourcesSpec(in, out, s)
}

func autoConvert_v1beta1_ContainerResourcesSpec_To_v1alpha1_ContainerResourcesSpec(in *v1beta1.ContainerResourcesSpec, out *ContainerResourcesSpec, s conversion.Scope) error {
	out.ContainerName = in.ContainerName
	out.CPURequest = in.CPURequest
	out.MemoryRequest = in.MemoryRequest
	out.CPULimit = in.CPULimit
	out.MemoryLimit = in.MemoryLimit
	return nil
}

// Convert_v1beta1_ContainerResourcesSpec_To_v1alpha1_ContainerResourcesSpec is an autogenerated conversion function.
func Convert_v1beta1_ContainerResourcesSpec_To_v1alpha1_ContainerResourcesSpec(in *v1beta1.ContainerResourcesSpec, out *ContainerResourcesSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_ContainerResourcesSpec_To_v1alpha1_ContainerResourcesSpec(in, out, s)
}

func autoConvert_v1alpha1_ErrorSummary_To_v1beta1_ErrorSummary(in *ErrorSummary, out *v1beta1.ErrorSummary, s conversion.Scope) error {
	out.TotalCount = in.TotalCount
	out.Truncated = in.Truncated
	out.ErrorCountAfterTruncation = in.ErrorCountAfterTruncation
	return nil
}

// Convert_v1alpha1_ErrorSummary_To_v1beta1_ErrorSummary is an autogenerated conversion function.
func Convert_v1alpha1_ErrorSummary_To_v1beta1_ErrorSummary(in *ErrorSummary, out *v1beta1.ErrorSummary, s conversion.Scope) error {
	return autoConvert_v1alpha1_ErrorSummary_To_v1beta1_ErrorSummary(in, out, s)
}

func autoConvert_v1beta1_ErrorSummary_To_v1alpha1_ErrorSummary(in *v1beta1.ErrorSummary, out *ErrorSummary, s conversion.Scope) error {
	out.TotalCount = in.TotalCount
	out.Truncated = in.Truncated
	out.ErrorCountAfterTruncation = in.ErrorCountAfterTruncation
	return nil
}

// Convert_v1beta1_ErrorSummary_To_v1alpha1_ErrorSummary is an autogenerated conversion function.
func Convert_v1beta1_ErrorSummary_To_v1alpha1_ErrorSummary(in *v1beta1.ErrorSummary, out *ErrorSummary, s conversion.Scope) error {
	return autoConvert_v1beta1_ErrorSummary_To_v1alpha1_ErrorSummary(in, out, s)
}

func autoConvert_v1alpha1_Git_To_v1beta1_Git(in *Git, out *v1beta1.Git, s conversion.Scope) error {
	out.Repo = in.Repo
	out.Branch = in.Branch
	out.Revision = in.Revision
	out.Dir = in.Dir
	out.Period = in.Period
	out.Auth = configsync.AuthType(in.Auth)
	out.GCPServiceAccountEmail = in.GCPServiceAccountEmail
	out.Proxy = in.Proxy
	out.SecretRef = (*v1beta1.SecretReference)(unsafe.Pointer(in.SecretRef))
	out.NoSSLVerify = in.NoSSLVerify
	out.CACertSecretRef = (*v1beta1.SecretReference)(unsafe.Pointer(in.CACertSecretRef))
	return nil
}

// Convert_v1alpha1_Git_To_v1beta1_Git is an autogenerated conversion function.
func Convert_v1alpha1_Git_To_v1beta1_Git(in *Git, out *v1beta1.Git, s conversion.Scope) error {
	return autoConvert_v1alpha1_Git_To_v1beta1_Git(in, out, s)
}

func autoConvert_v1beta1_Git_To_v1alpha1_Git(in *v1beta1.Git, out *Git, s conversion.Scope) error {
	out.Repo = in.Repo
	out.Branch = in.Branch
	out.Revision = in.Revision
	out.Dir = in.Dir
	out.Period = in.Period
	out.Auth = configsync.AuthType(in.Auth)
	out.GCPServiceAccountEmail = in.GCPServiceAccountEmail
	out.Proxy = in.Proxy
	out.SecretRef = (*SecretReference)(unsafe.Pointer(in.SecretRef))
	out.NoSSLVerify = in.NoSSLVerify
	out.CACertSecretRef = (*SecretReference)(unsafe.Pointer(in.CACertSecretRef))
	return nil
}

// Convert_v1beta1_Git_To_v1alpha1_Git is an autogenerated conversion function.
func Convert_v1beta1_Git_To_v1alpha1_Git(in *v1beta1.Git, out *Git, s conversion.Scope) error {
	return autoConvert_v1beta1_Git_To_v1alpha1_Git(in, out, s)
}

func autoConvert_v1alpha1_GitStatus_To_v1beta1_GitStatus(in *GitStatus, out *v1beta1.GitStatus, s conversion.Scope) error {
	out.Repo = in.Repo
	out.Revision = in.Revision
	out.Branch = in.Branch
	out.Dir = in.Dir
	return nil
}

// Convert_v1alpha1_GitStatus_To_v1beta1_GitStatus is an autogenerated conversion function.
func Convert_v1alpha1_GitStatus_To_v1beta1_GitStatus(in *GitStatus, out *v1beta1.GitStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_GitStatus_To_v1beta1_GitStatus(in, out, s)
}

func autoConvert_v1beta1_GitStatus_To_v1alpha1_GitStatus(in *v1beta1.GitStatus, out *GitStatus, s conversion.Scope) error {
	out.Repo = in.Repo
	out.Revision = in.Revision
	out.Branch = in.Branch
	out.Dir = in.Dir
	return nil
}

// Convert_v1beta1_GitStatus_To_v1alpha1_GitStatus is an autogenerated conversion function.
func Convert_v1beta1_GitStatus_To_v1alpha1_GitStatus(in *v1beta1.GitStatus, out *GitStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_GitStatus_To_v1alpha1_GitStatus(in, out, s)
}

func autoConvert_v1alpha1_HelmBase_To_v1beta1_HelmBase(in *HelmBase, out *v1beta1.HelmBase, s conversion.Scope) error {
	out.Repo = in.Repo
	out.Chart = in.Chart
	out.Version = in.Version
	out.ReleaseName = in.ReleaseName
	out.Values = (*v1.JSON)(unsafe.Pointer(in.Values))
	out.ValuesFileRefs = *(*[]v1beta1.ValuesFileRef)(unsafe.Pointer(&in.ValuesFileRefs))
	out.IncludeCRDs = in.IncludeCRDs
	out.Period = in.Period
	out.Auth = configsync.AuthType(in.Auth)
	out.GCPServiceAccountEmail = in.GCPServiceAccountEmail
	out.SecretRef = (*v1beta1.SecretReference)(unsafe.Pointer(in.SecretRef))
	return nil
}

// Convert_v1alpha1_HelmBase_To_v1beta1_HelmBase is an autogenerated conversion function.
func Convert_v1alpha1_HelmBase_To_v1beta1_HelmBase(in *HelmBase, out *v1beta1.HelmBase, s conversion.Scope) error {
	return autoConvert_v1alpha1_HelmBase_To_v1beta1_HelmBase(in, out, s)
}

func autoConvert_v1beta1_HelmBase_To_v1alpha1_HelmBase(in *v1beta1.HelmBase, out *HelmBase, s conversion.Scope) error {
	out.Repo = in.Repo
	out.Chart = in.Chart
	out.Version = in.Version
	out.ReleaseName = in.ReleaseName
	out.Values = (*v1.JSON)(unsafe.Pointer(in.Values))
	out.ValuesFileRefs = *(*[]ValuesFileRef)(unsafe.Pointer(&in.ValuesFileRefs))
	out.IncludeCRDs = in.IncludeCRDs
	out.Period = in.Period
	out.Auth = configsync.AuthType(in.Auth)
	out.GCPServiceAccountEmail = in.GCPServiceAccountEmail
	out.SecretRef = (*SecretReference)(unsafe.Pointer(in.SecretRef))
	return nil
}

func autoConvert_v1alpha1_HelmRepoSync_To_v1beta1_HelmRepoSync(in *HelmRepoSync, out *v1beta1.HelmRepoSync, s conversion.Scope) error {
	if err := Convert_v1alpha1_HelmBase_To_v1beta1_HelmBase(&in.HelmBase, &out.HelmBase, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_HelmRepoSync_To_v1beta1_HelmRepoSync is an autogenerated conversion function.
func Convert_v1alpha1_HelmRepoSync_To_v1beta1_HelmRepoSync(in *HelmRepoSync, out *v1beta1.HelmRepoSync, s conversion.Scope) error {
	return autoConvert_v1alpha1_HelmRepoSync_To_v1beta1_HelmRepoSync(in, out, s)
}

func autoConvert_v1beta1_HelmRepoSync_To_v1alpha1_HelmRepoSync(in *v1beta1.HelmRepoSync, out *HelmRepoSync, s conversion.Scope) error {
	if err := Convert_v1beta1_HelmBase_To_v1alpha1_HelmBase(&in.HelmBase, &out.HelmBase, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_HelmRepoSync_To_v1alpha1_HelmRepoSync is an autogenerated conversion function.
func Convert_v1beta1_HelmRepoSync_To_v1alpha1_HelmRepoSync(in *v1beta1.HelmRepoSync, out *HelmRepoSync, s conversion.Scope) error {
	return autoConvert_v1beta1_HelmRepoSync_To_v1alpha1_HelmRepoSync(in, out, s)
}

func autoConvert_v1alpha1_HelmRootSync_To_v1beta1_HelmRootSync(in *HelmRootSync, out *v1beta1.HelmRootSync, s conversion.Scope) error {
	if err := Convert_v1alpha1_HelmBase_To_v1beta1_HelmBase(&in.HelmBase, &out.HelmBase, s); err != nil {
		return err
	}
	out.Namespace = in.Namespace
	out.DeployNamespace = in.DeployNamespace
	return nil
}

// Convert_v1alpha1_HelmRootSync_To_v1beta1_HelmRootSync is an autogenerated conversion function.
func Convert_v1alpha1_HelmRootSync_To_v1beta1_HelmRootSync(in *HelmRootSync, out *v1beta1.HelmRootSync, s conversion.Scope) error {
	return autoConvert_v1alpha1_HelmRootSync_To_v1beta1_HelmRootSync(in, out, s)
}

func autoConvert_v1beta1_HelmRootSync_To_v1alpha1_HelmRootSync(in *v1beta1.HelmRootSync, out *HelmRootSync, s conversion.Scope) error {
	if err := Convert_v1beta1_HelmBase_To_v1alpha1_HelmBase(&in.HelmBase, &out.HelmBase, s); err != nil {
		return err
	}
	out.Namespace = in.Namespace
	out.DeployNamespace = in.DeployNamespace
	return nil
}

func autoConvert_v1alpha1_HelmStatus_To_v1beta1_HelmStatus(in *HelmStatus, out *v1beta1.HelmStatus, s conversion.Scope) error {
	out.Repo = in.Repo
	out.Version = in.Version
	out.Chart = in.Chart
	return nil
}

// Convert_v1alpha1_HelmStatus_To_v1beta1_HelmStatus is an autogenerated conversion function.
func Convert_v1alpha1_HelmStatus_To_v1beta1_HelmStatus(in *HelmStatus, out *v1beta1.HelmStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_HelmStatus_To_v1beta1_HelmStatus(in, out, s)
}

func autoConvert_v1beta1_HelmStatus_To_v1alpha1_HelmStatus(in *v1beta1.HelmStatus, out *HelmStatus, s conversion.Scope) error {
	out.Repo = in.Repo
	out.Version = in.Version
	out.Chart = in.Chart
	return nil
}

// Convert_v1beta1_HelmStatus_To_v1alpha1_HelmStatus is an autogenerated conversion function.
func Convert_v1beta1_HelmStatus_To_v1alpha1_HelmStatus(in *v1beta1.HelmStatus, out *HelmStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_HelmStatus_To_v1alpha1_HelmStatus(in, out, s)
}

func autoConvert_v1alpha1_Oci_To_v1beta1_Oci(in *Oci, out *v1beta1.Oci, s conversion.Scope) error {
	out.Image = in.Image
	out.Dir = in.Dir
	out.Period = in.Period
	out.Auth = configsync.AuthType(in.Auth)
	out.GCPServiceAccountEmail = in.GCPServiceAccountEmail
	return nil
}

// Convert_v1alpha1_Oci_To_v1beta1_Oci is an autogenerated conversion function.
func Convert_v1alpha1_Oci_To_v1beta1_Oci(in *Oci, out *v1beta1.Oci, s conversion.Scope) error {
	return autoConvert_v1alpha1_Oci_To_v1beta1_Oci(in, out, s)
}

func autoConvert_v1beta1_Oci_To_v1alpha1_Oci(in *v1beta1.Oci, out *Oci, s conversion.Scope) error {
	out.Image = in.Image
	out.Dir = in.Dir
	out.Period = in.Period
	out.Auth = configsync.AuthType(in.Auth)
	out.GCPServiceAccountEmail = in.GCPServiceAccountEmail
	return nil
}

// Convert_v1beta1_Oci_To_v1alpha1_Oci is an autogenerated conversion function.
func Convert_v1beta1_Oci_To_v1alpha1_Oci(in *v1beta1.Oci, out *Oci, s conversion.Scope) error {
	return autoConvert_v1beta1_Oci_To_v1alpha1_Oci(in, out, s)
}

func autoConvert_v1alpha1_OciStatus_To_v1beta1_OciStatus(in *OciStatus, out *v1beta1.OciStatus, s conversion.Scope) error {
	out.Image = in.Image
	out.Dir = in.Dir
	return nil
}

// Convert_v1alpha1_OciStatus_To_v1beta1_OciStatus is an autogenerated conversion function.
func Convert_v1alpha1_OciStatus_To_v1beta1_OciStatus(in *OciStatus, out *v1beta1.OciStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_OciStatus_To_v1beta1_OciStatus(in, out, s)
}

func autoConvert_v1beta1_OciStatus_To_v1alpha1_OciStatus(in *v1beta1.OciStatus, out *OciStatus, s conversion.Scope) error {
	out.Image = in.Image
	out.Dir = in.Dir
	return nil
}

// Convert_v1beta1_OciStatus_To_v1alpha1_OciStatus is an autogenerated conversion function.
func Convert_v1beta1_OciStatus_To_v1alpha1_OciStatus(in *v1beta1.OciStatus, out *OciStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_OciStatus_To_v1alpha1_OciStatus(in, out, s)
}

func autoConvert_v1alpha1_OverrideSpec_To_v1beta1_OverrideSpec(in *OverrideSpec, out *v1beta1.OverrideSpec, s conversion.Scope) error {
	out.Resources = *(*[]v1beta1.ContainerResourcesSpec)(unsafe.Pointer(&in.Resources))
	out.GitSyncDepth = (*int64)(unsafe.Pointer(in.GitSyncDepth))
	out.StatusMode = in.StatusMode
	out.ReconcileTimeout = (*metav1.Duration)(unsafe.Pointer(in.ReconcileTimeout))
	out.APIServerTimeout = (*metav1.Duration)(unsafe.Pointer(in.APIServerTimeout))
	out.EnableShellInRendering = (*bool)(unsafe.Pointer(in.EnableShellInRendering))
	out.LogLevels = *(*[]v1beta1.ContainerLogLevelOverride)(unsafe.Pointer(&in.LogLevels))
	return nil
}

// Convert_v1alpha1_OverrideSpec_To_v1beta1_OverrideSpec is an autogenerated conversion function.
func Convert_v1alpha1_OverrideSpec_To_v1beta1_OverrideSpec(in *OverrideSpec, out *v1beta1.OverrideSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_OverrideSpec_To_v1beta1_OverrideSpec(in, out, s)
}

func autoConvert_v1beta1_OverrideSpec_To_v1alpha1_OverrideSpec(in *v1beta1.OverrideSpec, out *OverrideSpec, s conversion.Scope) error {
	out.Resources = *(*[]ContainerResourcesSpec)(unsafe.Pointer(&in.Resources))
	out.GitSyncDepth = (*int64)(unsafe.Pointer(in.GitSyncDepth))
	out.StatusMode = in.StatusMode
	out.ReconcileTimeout = (*metav1.Duration)(unsafe.Pointer(in.ReconcileTimeout))
	out.APIServerTimeout = (*metav1.Duration)(unsafe.Pointer(in.APIServerTimeout))
	out.EnableShellInRendering = (*bool)(unsafe.Pointer(in.EnableShellInRendering))
	out.LogLevels = *(*[]ContainerLogLevelOverride)(unsafe.Pointer(&in.LogLevels))
	return nil
}

// Convert_v1beta1_OverrideSpec_To_v1alpha1_OverrideSpec is an autogenerated conversion function.
func Convert_v1beta1_OverrideSpec_To_v1alpha1_OverrideSpec(in *v1beta1.OverrideSpec, out *OverrideSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_OverrideSpec_To_v1alpha1_OverrideSpec(in, out, s)
}

func autoConvert_v1alpha1_RenderingStatus_To_v1beta1_RenderingStatus(in *RenderingStatus, out *v1beta1.RenderingStatus, s conversion.Scope) error {
	out.Git = (*v1beta1.GitStatus)(unsafe.Pointer(in.Git))
	out.Oci = (*v1beta1.OciStatus)(unsafe.Pointer(in.Oci))
	out.Helm = (*v1beta1.HelmStatus)(unsafe.Pointer(in.Helm))
	out.Commit = in.Commit
	out.Message = in.Message
	out.LastUpdate = in.LastUpdate
	out.Errors = *(*[]v1beta1.ConfigSyncError)(unsafe.Pointer(&in.Errors))
	out.ErrorSummary = (*v1beta1.ErrorSummary)(unsafe.Pointer(in.ErrorSummary))
	return nil
}

// Convert_v1alpha1_RenderingStatus_To_v1beta1_RenderingStatus is an autogenerated conversion function.
func Convert_v1alpha1_RenderingStatus_To_v1beta1_RenderingStatus(in *RenderingStatus, out *v1beta1.RenderingStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_RenderingStatus_To_v1beta1_RenderingStatus(in, out, s)
}

func autoConvert_v1beta1_RenderingStatus_To_v1alpha1_RenderingStatus(in *v1beta1.RenderingStatus, out *RenderingStatus, s conversion.Scope) error {
	out.Git = (*GitStatus)(unsafe.Pointer(in.Git))
	out.Oci = (*OciStatus)(unsafe.Pointer(in.Oci))
	out.Helm = (*HelmStatus)(unsafe.Pointer(in.Helm))
	out.Commit = in.Commit
	out.LastUpdate = in.LastUpdate
	out.Message = in.Message
	out.Errors = *(*[]ConfigSyncError)(unsafe.Pointer(&in.Errors))
	out.ErrorSummary = (*ErrorSummary)(unsafe.Pointer(in.ErrorSummary))
	return nil
}

// Convert_v1beta1_RenderingStatus_To_v1alpha1_RenderingStatus is an autogenerated conversion function.
func Convert_v1beta1_RenderingStatus_To_v1alpha1_RenderingStatus(in *v1beta1.RenderingStatus, out *RenderingStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_RenderingStatus_To_v1alpha1_RenderingStatus(in, out, s)
}

func autoConvert_v1alpha1_RepoSync_To_v1beta1_RepoSync(in *RepoSync, out *v1beta1.RepoSync, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_RepoSyncSpec_To_v1beta1_RepoSyncSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_RepoSyncStatus_To_v1beta1_RepoSyncStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_RepoSync_To_v1beta1_RepoSync is an autogenerated conversion function.
func Convert_v1alpha1_RepoSync_To_v1beta1_RepoSync(in *RepoSync, out *v1beta1.RepoSync, s conversion.Scope) error {
	return autoConvert_v1alpha1_RepoSync_To_v1beta1_RepoSync(in, out, s)
}

func autoConvert_v1beta1_RepoSync_To_v1alpha1_RepoSync(in *v1beta1.RepoSync, out *RepoSync, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_RepoSyncSpec_To_v1alpha1_RepoSyncSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_RepoSyncStatus_To_v1alpha1_RepoSyncStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_RepoSync_To_v1alpha1_RepoSync is an autogenerated conversion function.
func Convert_v1beta1_RepoSync_To_v1alpha1_RepoSync(in *v1beta1.RepoSync, out *RepoSync, s conversion.Scope) error {
	return autoConvert_v1beta1_RepoSync_To_v1alpha1_RepoSync(in, out, s)
}

func autoConvert_v1alpha1_RepoSyncCondition_To_v1beta1_RepoSyncCondition(in *RepoSyncCondition, out *v1beta1.RepoSyncCondition, s conversion.Scope) error {
	out.Type = v1beta1.RepoSyncConditionType(in.Type)
	out.Status = metav1.ConditionStatus(in.Status)
	out.LastUpdateTime = in.LastUpdateTime
	out.LastTransitionTime = in.LastTransitionTime
	out.Reason = in.Reason
	out.Message = in.Message
	out.Commit = in.Commit
	out.Errors = *(*[]v1beta1.ConfigSyncError)(unsafe.Pointer(&in.Errors))
	out.ErrorSourceRefs = *(*[]v1beta1.ErrorSource)(unsafe.Pointer(&in.ErrorSourceRefs))
	out.ErrorSummary = (*v1beta1.ErrorSummary)(unsafe.Pointer(in.ErrorSummary))
	return nil
}

// Convert_v1alpha1_RepoSyncCondition_To_v1beta1_RepoSyncCondition is an autogenerated conversion function.
func Convert_v1alpha1_RepoSyncCondition_To_v1beta1_RepoSyncCondition(in *RepoSyncCondition, out *v1beta1.RepoSyncCondition, s conversion.Scope) error {
	return autoConvert_v1alpha1_RepoSyncCondition_To_v1beta1_RepoSyncCondition(in, out, s)
}

func autoConvert_v1beta1_RepoSyncCondition_To_v1alpha1_RepoSyncCondition(in *v1beta1.RepoSyncCondition, out *RepoSyncCondition, s conversion.Scope) error {
	out.Type = RepoSyncConditionType(in.Type)
	out.Status = metav1.ConditionStatus(in.Status)
	out.LastUpdateTime = in.LastUpdateTime
	out.LastTransitionTime = in.LastTransitionTime
	out.Reason = in.Reason
	out.Message = in.Message
	out.Commit = in.Commit
	out.Errors = *(*[]ConfigSyncError)(unsafe.Pointer(&in.Errors))
	out.ErrorSourceRefs = *(*[]ErrorSource)(unsafe.Pointer(&in.ErrorSourceRefs))
	out.ErrorSummary = (*ErrorSummary)(unsafe.Pointer(in.ErrorSummary))
	return nil
}

// Convert_v1beta1_RepoSyncCondition_To_v1alpha1_RepoSyncCondition is an autogenerated conversion function.
func Convert_v1beta1_RepoSyncCondition_To_v1alpha1_RepoSyncCondition(in *v1beta1.RepoSyncCondition, out *RepoSyncCondition, s conversion.Scope) error {
	return autoConvert_v1beta1_RepoSyncCondition_To_v1alpha1_RepoSyncCondition(in, out, s)
}

func autoConvert_v1alpha1_RepoSyncList_To_v1beta1_RepoSyncList(in *RepoSyncList, out *v1beta1.RepoSyncList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1beta1.RepoSync, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_RepoSync_To_v1beta1_RepoSync(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_RepoSyncList_To_v1beta1_RepoSyncList is an autogenerated conversion function.
func Convert_v1alpha1_RepoSyncList_To_v1beta1_RepoSyncList(in *RepoSyncList, out *v1beta1.RepoSyncList, s conversion.Scope) error {
	return autoConvert_v1alpha1_RepoSyncList_To_v1beta1_RepoSyncList(in, out, s)
}

func autoConvert_v1beta1_RepoSyncList_To_v1alpha1_RepoSyncList(in *v1beta1.RepoSyncList, out *RepoSyncList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RepoSync, len(*in))
		for i := range *in {
			if err := Convert_v1beta1_RepoSync_To_v1alpha1_RepoSync(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta1_RepoSyncList_To_v1alpha1_RepoSyncList is an autogenerated conversion function.
func Convert_v1beta1_RepoSyncList_To_v1alpha1_RepoSyncList(in *v1beta1.RepoSyncList, out *RepoSyncList, s conversion.Scope) error {
	return autoConvert_v1beta1_RepoSyncList_To_v1alpha1_RepoSyncList(in, out, s)
}

func autoConvert_v1alpha1_RepoSyncOverrideSpec_To_v1beta1_RepoSyncOverrideSpec(in *RepoSyncOverrideSpec, out *v1beta1.RepoSyncOverrideSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_OverrideSpec_To_v1beta1_OverrideSpec(&in.OverrideSpec, &out.OverrideSpec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_RepoSyncOverrideSpec_To_v1beta1_RepoSyncOverrideSpec is an autogenerated conversion function.
func Convert_v1alpha1_RepoSyncOverrideSpec_To_v1beta1_RepoSyncOverrideSpec(in *RepoSyncOverrideSpec, out *v1beta1.RepoSyncOverrideSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_RepoSyncOverrideSpec_To_v1beta1_RepoSyncOverrideSpec(in, out, s)
}

func autoConvert_v1beta1_RepoSyncOverrideSpec_To_v1alpha1_RepoSyncOverrideSpec(in *v1beta1.RepoSyncOverrideSpec, out *RepoSyncOverrideSpec, s conversion.Scope) error {
	if err := Convert_v1beta1_OverrideSpec_To_v1alpha1_OverrideSpec(&in.OverrideSpec, &out.OverrideSpec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_RepoSyncOverrideSpec_To_v1alpha1_RepoSyncOverrideSpec is an autogenerated conversion function.
func Convert_v1beta1_RepoSyncOverrideSpec_To_v1alpha1_RepoSyncOverrideSpec(in *v1beta1.RepoSyncOverrideSpec, out *RepoSyncOverrideSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_RepoSyncOverrideSpec_To_v1alpha1_RepoSyncOverrideSpec(in, out, s)
}

func autoConvert_v1alpha1_RepoSyncSpec_To_v1beta1_RepoSyncSpec(in *RepoSyncSpec, out *v1beta1.RepoSyncSpec, s conversion.Scope) error {
	out.SourceFormat = in.SourceFormat
	out.SourceType = in.SourceType
	out.Git = (*v1beta1.Git)(unsafe.Pointer(in.Git))
	out.Oci = (*v1beta1.Oci)(unsafe.Pointer(in.Oci))
	if in.Helm != nil {
		in, out := &in.Helm, &out.Helm
		*out = new(v1beta1.HelmRepoSync)
		if err := Convert_v1alpha1_HelmRepoSync_To_v1beta1_HelmRepoSync(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.Helm = nil
	}
	out.Override = (*v1beta1.RepoSyncOverrideSpec)(unsafe.Pointer(in.Override))
	return nil
}

// Convert_v1alpha1_RepoSyncSpec_To_v1beta1_RepoSyncSpec is an autogenerated conversion function.
func Convert_v1alpha1_RepoSyncSpec_To_v1beta1_RepoSyncSpec(in *RepoSyncSpec, out *v1beta1.RepoSyncSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_RepoSyncSpec_To_v1beta1_RepoSyncSpec(in, out, s)
}

func autoConvert_v1beta1_RepoSyncSpec_To_v1alpha1_RepoSyncSpec(in *v1beta1.RepoSyncSpec, out *RepoSyncSpec, s conversion.Scope) error {
	out.SourceFormat = in.SourceFormat
	out.SourceType = in.SourceType
	out.Git = (*Git)(unsafe.Pointer(in.Git))
	out.Oci = (*Oci)(unsafe.Pointer(in.Oci))
	if in.Helm != nil {
		in, out := &in.Helm, &out.Helm
		*out = new(HelmRepoSync)
		if err := Convert_v1beta1_HelmRepoSync_To_v1alpha1_HelmRepoSync(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.Helm = nil
	}
	out.Override = (*RepoSyncOverrideSpec)(unsafe.Pointer(in.Override))
	return nil
}

// Convert_v1beta1_RepoSyncSpec_To_v1alpha1_RepoSyncSpec is an autogenerated conversion function.
func Convert_v1beta1_RepoSyncSpec_To_v1alpha1_RepoSyncSpec(in *v1beta1.RepoSyncSpec, out *RepoSyncSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_RepoSyncSpec_To_v1alpha1_RepoSyncSpec(in, out, s)
}

func autoConvert_v1alpha1_RepoSyncStatus_To_v1beta1_RepoSyncStatus(in *RepoSyncStatus, out *v1beta1.RepoSyncStatus, s conversion.Scope) error {
	if err := Convert_v1alpha1_Status_To_v1beta1_Status(&in.Status, &out.Status, s); err != nil {
		return err
	}
	out.Conditions = *(*[]v1beta1.RepoSyncCondition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha1_RepoSyncStatus_To_v1beta1_RepoSyncStatus is an autogenerated conversion function.
func Convert_v1alpha1_RepoSyncStatus_To_v1beta1_RepoSyncStatus(in *RepoSyncStatus, out *v1beta1.RepoSyncStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_RepoSyncStatus_To_v1beta1_RepoSyncStatus(in, out, s)
}

func autoConvert_v1beta1_RepoSyncStatus_To_v1alpha1_RepoSyncStatus(in *v1beta1.RepoSyncStatus, out *RepoSyncStatus, s conversion.Scope) error {
	if err := Convert_v1beta1_Status_To_v1alpha1_Status(&in.Status, &out.Status, s); err != nil {
		return err
	}
	out.Conditions = *(*[]RepoSyncCondition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1beta1_RepoSyncStatus_To_v1alpha1_RepoSyncStatus is an autogenerated conversion function.
func Convert_v1beta1_RepoSyncStatus_To_v1alpha1_RepoSyncStatus(in *v1beta1.RepoSyncStatus, out *RepoSyncStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_RepoSyncStatus_To_v1alpha1_RepoSyncStatus(in, out, s)
}

func autoConvert_v1alpha1_ResourceRef_To_v1beta1_ResourceRef(in *ResourceRef, out *v1beta1.ResourceRef, s conversion.Scope) error {
	out.SourcePath = in.SourcePath
	out.Name = in.Name
	out.Namespace = in.Namespace
	out.GVK = in.GVK
	return nil
}

// Convert_v1alpha1_ResourceRef_To_v1beta1_ResourceRef is an autogenerated conversion function.
func Convert_v1alpha1_ResourceRef_To_v1beta1_ResourceRef(in *ResourceRef, out *v1beta1.ResourceRef, s conversion.Scope) error {
	return autoConvert_v1alpha1_ResourceRef_To_v1beta1_ResourceRef(in, out, s)
}

func autoConvert_v1beta1_ResourceRef_To_v1alpha1_ResourceRef(in *v1beta1.ResourceRef, out *ResourceRef, s conversion.Scope) error {
	out.SourcePath = in.SourcePath
	out.Name = in.Name
	out.Namespace = in.Namespace
	out.GVK = in.GVK
	return nil
}

// Convert_v1beta1_ResourceRef_To_v1alpha1_ResourceRef is an autogenerated conversion function.
func Convert_v1beta1_ResourceRef_To_v1alpha1_ResourceRef(in *v1beta1.ResourceRef, out *ResourceRef, s conversion.Scope) error {
	return autoConvert_v1beta1_ResourceRef_To_v1alpha1_ResourceRef(in, out, s)
}

func autoConvert_v1alpha1_RootSync_To_v1beta1_RootSync(in *RootSync, out *v1beta1.RootSync, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_RootSyncSpec_To_v1beta1_RootSyncSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_RootSyncStatus_To_v1beta1_RootSyncStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_RootSync_To_v1beta1_RootSync is an autogenerated conversion function.
func Convert_v1alpha1_RootSync_To_v1beta1_RootSync(in *RootSync, out *v1beta1.RootSync, s conversion.Scope) error {
	return autoConvert_v1alpha1_RootSync_To_v1beta1_RootSync(in, out, s)
}

func autoConvert_v1beta1_RootSync_To_v1alpha1_RootSync(in *v1beta1.RootSync, out *RootSync, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_RootSyncSpec_To_v1alpha1_RootSyncSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_RootSyncStatus_To_v1alpha1_RootSyncStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_RootSync_To_v1alpha1_RootSync is an autogenerated conversion function.
func Convert_v1beta1_RootSync_To_v1alpha1_RootSync(in *v1beta1.RootSync, out *RootSync, s conversion.Scope) error {
	return autoConvert_v1beta1_RootSync_To_v1alpha1_RootSync(in, out, s)
}

func autoConvert_v1alpha1_RootSyncCondition_To_v1beta1_RootSyncCondition(in *RootSyncCondition, out *v1beta1.RootSyncCondition, s conversion.Scope) error {
	out.Type = v1beta1.RootSyncConditionType(in.Type)
	out.Status = metav1.ConditionStatus(in.Status)
	out.LastUpdateTime = in.LastUpdateTime
	out.LastTransitionTime = in.LastTransitionTime
	out.Reason = in.Reason
	out.Message = in.Message
	out.Commit = in.Commit
	out.Errors = *(*[]v1beta1.ConfigSyncError)(unsafe.Pointer(&in.Errors))
	out.ErrorSourceRefs = *(*[]v1beta1.ErrorSource)(unsafe.Pointer(&in.ErrorSourceRefs))
	out.ErrorSummary = (*v1beta1.ErrorSummary)(unsafe.Pointer(in.ErrorSummary))
	return nil
}

// Convert_v1alpha1_RootSyncCondition_To_v1beta1_RootSyncCondition is an autogenerated conversion function.
func Convert_v1alpha1_RootSyncCondition_To_v1beta1_RootSyncCondition(in *RootSyncCondition, out *v1beta1.RootSyncCondition, s conversion.Scope) error {
	return autoConvert_v1alpha1_RootSyncCondition_To_v1beta1_RootSyncCondition(in, out, s)
}

func autoConvert_v1beta1_RootSyncCondition_To_v1alpha1_RootSyncCondition(in *v1beta1.RootSyncCondition, out *RootSyncCondition, s conversion.Scope) error {
	out.Type = RootSyncConditionType(in.Type)
	out.Status = metav1.ConditionStatus(in.Status)
	out.LastUpdateTime = in.LastUpdateTime
	out.LastTransitionTime = in.LastTransitionTime
	out.Reason = in.Reason
	out.Message = in.Message
	out.Commit = in.Commit
	out.Errors = *(*[]ConfigSyncError)(unsafe.Pointer(&in.Errors))
	out.ErrorSourceRefs = *(*[]ErrorSource)(unsafe.Pointer(&in.ErrorSourceRefs))
	out.ErrorSummary = (*ErrorSummary)(unsafe.Pointer(in.ErrorSummary))
	return nil
}

// Convert_v1beta1_RootSyncCondition_To_v1alpha1_RootSyncCondition is an autogenerated conversion function.
func Convert_v1beta1_RootSyncCondition_To_v1alpha1_RootSyncCondition(in *v1beta1.RootSyncCondition, out *RootSyncCondition, s conversion.Scope) error {
	return autoConvert_v1beta1_RootSyncCondition_To_v1alpha1_RootSyncCondition(in, out, s)
}

func autoConvert_v1alpha1_RootSyncList_To_v1beta1_RootSyncList(in *RootSyncList, out *v1beta1.RootSyncList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1beta1.RootSync, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_RootSync_To_v1beta1_RootSync(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_RootSyncList_To_v1beta1_RootSyncList is an autogenerated conversion function.
func Convert_v1alpha1_RootSyncList_To_v1beta1_RootSyncList(in *RootSyncList, out *v1beta1.RootSyncList, s conversion.Scope) error {
	return autoConvert_v1alpha1_RootSyncList_To_v1beta1_RootSyncList(in, out, s)
}

func autoConvert_v1beta1_RootSyncList_To_v1alpha1_RootSyncList(in *v1beta1.RootSyncList, out *RootSyncList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RootSync, len(*in))
		for i := range *in {
			if err := Convert_v1beta1_RootSync_To_v1alpha1_RootSync(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta1_RootSyncList_To_v1alpha1_RootSyncList is an autogenerated conversion function.
func Convert_v1beta1_RootSyncList_To_v1alpha1_RootSyncList(in *v1beta1.RootSyncList, out *RootSyncList, s conversion.Scope) error {
	return autoConvert_v1beta1_RootSyncList_To_v1alpha1_RootSyncList(in, out, s)
}

func autoConvert_v1alpha1_RootSyncOverrideSpec_To_v1beta1_RootSyncOverrideSpec(in *RootSyncOverrideSpec, out *v1beta1.RootSyncOverrideSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_OverrideSpec_To_v1beta1_OverrideSpec(&in.OverrideSpec, &out.OverrideSpec, s); err != nil {
		return err
	}
	out.NamespaceStrategy = configsync.NamespaceStrategy(in.NamespaceStrategy)
	out.RoleRefs = *(*[]v1beta1.RootSyncRoleRef)(unsafe.Pointer(&in.RoleRefs))
	return nil
}

// Convert_v1alpha1_RootSyncOverrideSpec_To_v1beta1_RootSyncOverrideSpec is an autogenerated conversion function.
func Convert_v1alpha1_RootSyncOverrideSpec_To_v1beta1_RootSyncOverrideSpec(in *RootSyncOverrideSpec, out *v1beta1.RootSyncOverrideSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_RootSyncOverrideSpec_To_v1beta1_RootSyncOverrideSpec(in, out, s)
}

func autoConvert_v1beta1_RootSyncOverrideSpec_To_v1alpha1_RootSyncOverrideSpec(in *v1beta1.RootSyncOverrideSpec, out *RootSyncOverrideSpec, s conversion.Scope) error {
	if err := Convert_v1beta1_OverrideSpec_To_v1alpha1_OverrideSpec(&in.OverrideSpec, &out.OverrideSpec, s); err != nil {
		return err
	}
	out.NamespaceStrategy = configsync.NamespaceStrategy(in.NamespaceStrategy)
	out.RoleRefs = *(*[]RootSyncRoleRef)(unsafe.Pointer(&in.RoleRefs))
	return nil
}

// Convert_v1beta1_RootSyncOverrideSpec_To_v1alpha1_RootSyncOverrideSpec is an autogenerated conversion function.
func Convert_v1beta1_RootSyncOverrideSpec_To_v1alpha1_RootSyncOverrideSpec(in *v1beta1.RootSyncOverrideSpec, out *RootSyncOverrideSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_RootSyncOverrideSpec_To_v1alpha1_RootSyncOverrideSpec(in, out, s)
}

func autoConvert_v1alpha1_RootSyncRoleRef_To_v1beta1_RootSyncRoleRef(in *RootSyncRoleRef, out *v1beta1.RootSyncRoleRef, s conversion.Scope) error {
	out.Kind = in.Kind
	out.Name = in.Name
	out.Namespace = in.Namespace
	return nil
}

// Convert_v1alpha1_RootSyncRoleRef_To_v1beta1_RootSyncRoleRef is an autogenerated conversion function.
func Convert_v1alpha1_RootSyncRoleRef_To_v1beta1_RootSyncRoleRef(in *RootSyncRoleRef, out *v1beta1.RootSyncRoleRef, s conversion.Scope) error {
	return autoConvert_v1alpha1_RootSyncRoleRef_To_v1beta1_RootSyncRoleRef(in, out, s)
}

func autoConvert_v1beta1_RootSyncRoleRef_To_v1alpha1_RootSyncRoleRef(in *v1beta1.RootSyncRoleRef, out *RootSyncRoleRef, s conversion.Scope) error {
	out.Kind = in.Kind
	out.Name = in.Name
	out.Namespace = in.Namespace
	return nil
}

// Convert_v1beta1_RootSyncRoleRef_To_v1alpha1_RootSyncRoleRef is an autogenerated conversion function.
func Convert_v1beta1_RootSyncRoleRef_To_v1alpha1_RootSyncRoleRef(in *v1beta1.RootSyncRoleRef, out *RootSyncRoleRef, s conversion.Scope) error {
	return autoConvert_v1beta1_RootSyncRoleRef_To_v1alpha1_RootSyncRoleRef(in, out, s)
}

func autoConvert_v1alpha1_RootSyncSpec_To_v1beta1_RootSyncSpec(in *RootSyncSpec, out *v1beta1.RootSyncSpec, s conversion.Scope) error {
	out.SourceFormat = in.SourceFormat
	out.SourceType = in.SourceType
	out.Git = (*v1beta1.Git)(unsafe.Pointer(in.Git))
	out.Oci = (*v1beta1.Oci)(unsafe.Pointer(in.Oci))
	if in.Helm != nil {
		in, out := &in.Helm, &out.Helm
		*out = new(v1beta1.HelmRootSync)
		if err := Convert_v1alpha1_HelmRootSync_To_v1beta1_HelmRootSync(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.Helm = nil
	}
	out.Override = (*v1beta1.RootSyncOverrideSpec)(unsafe.Pointer(in.Override))
	return nil
}

// Convert_v1alpha1_RootSyncSpec_To_v1beta1_RootSyncSpec is an autogenerated conversion function.
func Convert_v1alpha1_RootSyncSpec_To_v1beta1_RootSyncSpec(in *RootSyncSpec, out *v1beta1.RootSyncSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_RootSyncSpec_To_v1beta1_RootSyncSpec(in, out, s)
}

func autoConvert_v1beta1_RootSyncSpec_To_v1alpha1_RootSyncSpec(in *v1beta1.RootSyncSpec, out *RootSyncSpec, s conversion.Scope) error {
	out.SourceFormat = in.SourceFormat
	out.SourceType = in.SourceType
	out.Git = (*Git)(unsafe.Pointer(in.Git))
	out.Oci = (*Oci)(unsafe.Pointer(in.Oci))
	if in.Helm != nil {
		in, out := &in.Helm, &out.Helm
		*out = new(HelmRootSync)
		if err := Convert_v1beta1_HelmRootSync_To_v1alpha1_HelmRootSync(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.Helm = nil
	}
	out.Override = (*RootSyncOverrideSpec)(unsafe.Pointer(in.Override))
	return nil
}

// Convert_v1beta1_RootSyncSpec_To_v1alpha1_RootSyncSpec is an autogenerated conversion function.
func Convert_v1beta1_RootSyncSpec_To_v1alpha1_RootSyncSpec(in *v1beta1.RootSyncSpec, out *RootSyncSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_RootSyncSpec_To_v1alpha1_RootSyncSpec(in, out, s)
}

func autoConvert_v1alpha1_RootSyncStatus_To_v1beta1_RootSyncStatus(in *RootSyncStatus, out *v1beta1.RootSyncStatus, s conversion.Scope) error {
	if err := Convert_v1alpha1_Status_To_v1beta1_Status(&in.Status, &out.Status, s); err != nil {
		return err
	}
	out.Conditions = *(*[]v1beta1.RootSyncCondition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha1_RootSyncStatus_To_v1beta1_RootSyncStatus is an autogenerated conversion function.
func Convert_v1alpha1_RootSyncStatus_To_v1beta1_RootSyncStatus(in *RootSyncStatus, out *v1beta1.RootSyncStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_RootSyncStatus_To_v1beta1_RootSyncStatus(in, out, s)
}

func autoConvert_v1beta1_RootSyncStatus_To_v1alpha1_RootSyncStatus(in *v1beta1.RootSyncStatus, out *RootSyncStatus, s conversion.Scope) error {
	if err := Convert_v1beta1_Status_To_v1alpha1_Status(&in.Status, &out.Status, s); err != nil {
		return err
	}
	out.Conditions = *(*[]RootSyncCondition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1beta1_RootSyncStatus_To_v1alpha1_RootSyncStatus is an autogenerated conversion function.
func Convert_v1beta1_RootSyncStatus_To_v1alpha1_RootSyncStatus(in *v1beta1.RootSyncStatus, out *RootSyncStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_RootSyncStatus_To_v1alpha1_RootSyncStatus(in, out, s)
}

func autoConvert_v1alpha1_SecretReference_To_v1beta1_SecretReference(in *SecretReference, out *v1beta1.SecretReference, s conversion.Scope) error {
	out.Name = in.Name
	return nil
}

// Convert_v1alpha1_SecretReference_To_v1beta1_SecretReference is an autogenerated conversion function.
func Convert_v1alpha1_SecretReference_To_v1beta1_SecretReference(in *SecretReference, out *v1beta1.SecretReference, s conversion.Scope) error {
	return autoConvert_v1alpha1_SecretReference_To_v1beta1_SecretReference(in, out, s)
}

func autoConvert_v1beta1_SecretReference_To_v1alpha1_SecretReference(in *v1beta1.SecretReference, out *SecretReference, s conversion.Scope) error {
	out.Name = in.Name
	return nil
}

// Convert_v1beta1_SecretReference_To_v1alpha1_SecretReference is an autogenerated conversion function.
func Convert_v1beta1_SecretReference_To_v1alpha1_SecretReference(in *v1beta1.SecretReference, out *SecretReference, s conversion.Scope) error {
	return autoConvert_v1beta1_SecretReference_To_v1alpha1_SecretReference(in, out, s)
}

func autoConvert_v1alpha1_SourceStatus_To_v1beta1_SourceStatus(in *SourceStatus, out *v1beta1.SourceStatus, s conversion.Scope) error {
	out.Git = (*v1beta1.GitStatus)(unsafe.Pointer(in.Git))
	out.Oci = (*v1beta1.OciStatus)(unsafe.Pointer(in.Oci))
	out.Helm = (*v1beta1.HelmStatus)(unsafe.Pointer(in.Helm))
	out.Commit = in.Commit
	out.LastUpdate = in.LastUpdate
	out.Errors = *(*[]v1beta1.ConfigSyncError)(unsafe.Pointer(&in.Errors))
	out.ErrorSummary = (*v1beta1.ErrorSummary)(unsafe.Pointer(in.ErrorSummary))
	return nil
}

// Convert_v1alpha1_SourceStatus_To_v1beta1_SourceStatus is an autogenerated conversion function.
func Convert_v1alpha1_SourceStatus_To_v1beta1_SourceStatus(in *SourceStatus, out *v1beta1.SourceStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_SourceStatus_To_v1beta1_SourceStatus(in, out, s)
}

func autoConvert_v1beta1_SourceStatus_To_v1alpha1_SourceStatus(in *v1beta1.SourceStatus, out *SourceStatus, s conversion.Scope) error {
	out.Git = (*GitStatus)(unsafe.Pointer(in.Git))
	out.Oci = (*OciStatus)(unsafe.Pointer(in.Oci))
	out.Helm = (*HelmStatus)(unsafe.Pointer(in.Helm))
	out.Commit = in.Commit
	out.LastUpdate = in.LastUpdate
	out.Errors = *(*[]ConfigSyncError)(unsafe.Pointer(&in.Errors))
	out.ErrorSummary = (*ErrorSummary)(unsafe.Pointer(in.ErrorSummary))
	return nil
}

// Convert_v1beta1_SourceStatus_To_v1alpha1_SourceStatus is an autogenerated conversion function.
func Convert_v1beta1_SourceStatus_To_v1alpha1_SourceStatus(in *v1beta1.SourceStatus, out *SourceStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_SourceStatus_To_v1alpha1_SourceStatus(in, out, s)
}

func autoConvert_v1alpha1_Status_To_v1beta1_Status(in *Status, out *v1beta1.Status, s conversion.Scope) error {
	out.ObservedGeneration = in.ObservedGeneration
	out.Reconciler = in.Reconciler
	out.LastSyncedCommit = in.LastSyncedCommit
	if err := Convert_v1alpha1_SourceStatus_To_v1beta1_SourceStatus(&in.Source, &out.Source, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_RenderingStatus_To_v1beta1_RenderingStatus(&in.Rendering, &out.Rendering, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_SyncStatus_To_v1beta1_SyncStatus(&in.Sync, &out.Sync, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Status_To_v1beta1_Status is an autogenerated conversion function.
func Convert_v1alpha1_Status_To_v1beta1_Status(in *Status, out *v1beta1.Status, s conversion.Scope) error {
	return autoConvert_v1alpha1_Status_To_v1beta1_Status(in, out, s)
}

func autoConvert_v1beta1_Status_To_v1alpha1_Status(in *v1beta1.Status, out *Status, s conversion.Scope) error {
	out.ObservedGeneration = in.ObservedGeneration
	out.Reconciler = in.Reconciler
	out.LastSyncedCommit = in.LastSyncedCommit
	if err := Convert_v1beta1_SourceStatus_To_v1alpha1_SourceStatus(&in.Source, &out.Source, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_RenderingStatus_To_v1alpha1_RenderingStatus(&in.Rendering, &out.Rendering, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_SyncStatus_To_v1alpha1_SyncStatus(&in.Sync, &out.Sync, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_Status_To_v1alpha1_Status is an autogenerated conversion function.
func Convert_v1beta1_Status_To_v1alpha1_Status(in *v1beta1.Status, out *Status, s conversion.Scope) error {
	return autoConvert_v1beta1_Status_To_v1alpha1_Status(in, out, s)
}

func autoConvert_v1alpha1_SyncStatus_To_v1beta1_SyncStatus(in *SyncStatus, out *v1beta1.SyncStatus, s conversion.Scope) error {
	out.Git = (*v1beta1.GitStatus)(unsafe.Pointer(in.Git))
	out.Oci = (*v1beta1.OciStatus)(unsafe.Pointer(in.Oci))
	out.Helm = (*v1beta1.HelmStatus)(unsafe.Pointer(in.Helm))
	out.Commit = in.Commit
	out.LastUpdate = in.LastUpdate
	out.Errors = *(*[]v1beta1.ConfigSyncError)(unsafe.Pointer(&in.Errors))
	out.ErrorSummary = (*v1beta1.ErrorSummary)(unsafe.Pointer(in.ErrorSummary))
	return nil
}

// Convert_v1alpha1_SyncStatus_To_v1beta1_SyncStatus is an autogenerated conversion function.
func Convert_v1alpha1_SyncStatus_To_v1beta1_SyncStatus(in *SyncStatus, out *v1beta1.SyncStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_SyncStatus_To_v1beta1_SyncStatus(in, out, s)
}

func autoConvert_v1beta1_SyncStatus_To_v1alpha1_SyncStatus(in *v1beta1.SyncStatus, out *SyncStatus, s conversion.Scope) error {
	out.Git = (*GitStatus)(unsafe.Pointer(in.Git))
	out.Oci = (*OciStatus)(unsafe.Pointer(in.Oci))
	out.Helm = (*HelmStatus)(unsafe.Pointer(in.Helm))
	out.Commit = in.Commit
	out.LastUpdate = in.LastUpdate
	out.Errors = *(*[]ConfigSyncError)(unsafe.Pointer(&in.Errors))
	out.ErrorSummary = (*ErrorSummary)(unsafe.Pointer(in.ErrorSummary))
	return nil
}

// Convert_v1beta1_SyncStatus_To_v1alpha1_SyncStatus is an autogenerated conversion function.
func Convert_v1beta1_SyncStatus_To_v1alpha1_SyncStatus(in *v1beta1.SyncStatus, out *SyncStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_SyncStatus_To_v1alpha1_SyncStatus(in, out, s)
}

func autoConvert_v1alpha1_ValuesFileRef_To_v1beta1_ValuesFileRef(in *ValuesFileRef, out *v1beta1.ValuesFileRef, s conversion.Scope) error {
	out.Name = in.Name
	out.DataKey = in.DataKey
	return nil
}

// Convert_v1alpha1_ValuesFileRef_To_v1beta1_ValuesFileRef is an autogenerated conversion function.
func Convert_v1alpha1_ValuesFileRef_To_v1beta1_ValuesFileRef(in *ValuesFileRef, out *v1beta1.ValuesFileRef, s conversion.Scope) error {
	return autoConvert_v1alpha1_ValuesFileRef_To_v1beta1_ValuesFileRef(in, out, s)
}

func autoConvert_v1beta1_ValuesFileRef_To_v1alpha1_ValuesFileRef(in *v1beta1.ValuesFileRef, out *ValuesFileRef, s conversion.Scope) error {
	out.Name = in.Name
	out.DataKey = in.DataKey
	return nil
}

// Convert_v1beta1_ValuesFileRef_To_v1alpha1_ValuesFileRef is an autogenerated conversion function.
func Convert_v1beta1_ValuesFileRef_To_v1alpha1_ValuesFileRef(in *v1beta1.ValuesFileRef, out *ValuesFileRef, s conversion.Scope) error {
	return autoConvert_v1beta1_ValuesFileRef_To_v1alpha1_ValuesFileRef(in, out, s)
}
