// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
	v1 "kpt.dev/configsync/pkg/api/configmanagement/v1"
)

// ClusterSelectorLister helps list ClusterSelectors.
// All objects returned here must be treated as read-only.
type ClusterSelectorLister interface {
	// List lists all ClusterSelectors in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.ClusterSelector, err error)
	// Get retrieves the ClusterSelector from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.ClusterSelector, error)
	ClusterSelectorListerExpansion
}

// clusterSelectorLister implements the ClusterSelectorLister interface.
type clusterSelectorLister struct {
	indexer cache.Indexer
}

// NewClusterSelectorLister returns a new ClusterSelectorLister.
func NewClusterSelectorLister(indexer cache.Indexer) ClusterSelectorLister {
	return &clusterSelectorLister{indexer: indexer}
}

// List lists all ClusterSelectors in the indexer.
func (s *clusterSelectorLister) List(selector labels.Selector) (ret []*v1.ClusterSelector, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.ClusterSelector))
	})
	return ret, err
}

// Get retrieves the ClusterSelector from the index for a given name.
func (s *clusterSelectorLister) Get(name string) (*v1.ClusterSelector, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("clusterselector"), name)
	}
	return obj.(*v1.ClusterSelector), nil
}
