// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
	v1 "kpt.dev/configsync/pkg/api/configmanagement/v1"
)

// NamespaceConfigLister helps list NamespaceConfigs.
// All objects returned here must be treated as read-only.
type NamespaceConfigLister interface {
	// List lists all NamespaceConfigs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.NamespaceConfig, err error)
	// Get retrieves the NamespaceConfig from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.NamespaceConfig, error)
	NamespaceConfigListerExpansion
}

// namespaceConfigLister implements the NamespaceConfigLister interface.
type namespaceConfigLister struct {
	indexer cache.Indexer
}

// NewNamespaceConfigLister returns a new NamespaceConfigLister.
func NewNamespaceConfigLister(indexer cache.Indexer) NamespaceConfigLister {
	return &namespaceConfigLister{indexer: indexer}
}

// List lists all NamespaceConfigs in the indexer.
func (s *namespaceConfigLister) List(selector labels.Selector) (ret []*v1.NamespaceConfig, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.NamespaceConfig))
	})
	return ret, err
}

// Get retrieves the NamespaceConfig from the index for a given name.
func (s *namespaceConfigLister) Get(name string) (*v1.NamespaceConfig, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("namespaceconfig"), name)
	}
	return obj.(*v1.NamespaceConfig), nil
}
