// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by cmd/gen-core-scoper/main.go. DO NOT EDIT

package discovery

import (
	"k8s.io/apimachinery/pkg/runtime/schema"
)

// CoreScoper returns a Scoper with the scopes of all core Kubernetes and Nomos
// types defined. Use this instead of building a Scoper from the response to an
// APIServer when one is unavailable.
func CoreScoper() Scoper {
	return Scoper{scope: map[schema.GroupKind]ScopeType{
		{Group: "", Kind: "ConfigMap"}:                                                  NamespaceScope,
		{Group: "", Kind: "Endpoints"}:                                                  NamespaceScope,
		{Group: "", Kind: "Event"}:                                                      NamespaceScope,
		{Group: "", Kind: "LimitRange"}:                                                 NamespaceScope,
		{Group: "", Kind: "Namespace"}:                                                  ClusterScope,
		{Group: "", Kind: "Node"}:                                                       ClusterScope,
		{Group: "", Kind: "PersistentVolumeClaim"}:                                      NamespaceScope,
		{Group: "", Kind: "PersistentVolume"}:                                           ClusterScope,
		{Group: "", Kind: "Pod"}:                                                        NamespaceScope,
		{Group: "", Kind: "PodTemplate"}:                                                NamespaceScope,
		{Group: "", Kind: "ReplicationController"}:                                      NamespaceScope,
		{Group: "", Kind: "ResourceQuota"}:                                              NamespaceScope,
		{Group: "", Kind: "Secret"}:                                                     NamespaceScope,
		{Group: "", Kind: "ServiceAccount"}:                                             NamespaceScope,
		{Group: "", Kind: "Service"}:                                                    NamespaceScope,
		{Group: "admissionregistration.k8s.io", Kind: "MutatingWebhookConfiguration"}:   ClusterScope,
		{Group: "admissionregistration.k8s.io", Kind: "ValidatingWebhookConfiguration"}: ClusterScope,
		{Group: "apiextensions.k8s.io", Kind: "CustomResourceDefinition"}:               ClusterScope,
		{Group: "apiregistration.k8s.io", Kind: "APIService"}:                           ClusterScope,
		{Group: "apps", Kind: "ControllerRevision"}:                                     NamespaceScope,
		{Group: "apps", Kind: "DaemonSet"}:                                              NamespaceScope,
		{Group: "apps", Kind: "Deployment"}:                                             NamespaceScope,
		{Group: "apps", Kind: "ReplicaSet"}:                                             NamespaceScope,
		{Group: "apps", Kind: "StatefulSet"}:                                            NamespaceScope,
		{Group: "autoscaling", Kind: "HorizontalPodAutoscaler"}:                         NamespaceScope,
		{Group: "batch", Kind: "CronJob"}:                                               NamespaceScope,
		{Group: "batch", Kind: "Job"}:                                                   NamespaceScope,
		{Group: "certificates.k8s.io", Kind: "CertificateSigningRequest"}:               ClusterScope,
		{Group: "cloud.google.com", Kind: "BackendConfig"}:                              NamespaceScope,
		{Group: "coordination.k8s.io", Kind: "Lease"}:                                   NamespaceScope,
		{Group: "extensions", Kind: "DaemonSet"}:                                        NamespaceScope,
		{Group: "extensions", Kind: "Deployment"}:                                       NamespaceScope,
		{Group: "extensions", Kind: "Ingress"}:                                          NamespaceScope,
		{Group: "extensions", Kind: "NetworkPolicy"}:                                    NamespaceScope,
		{Group: "extensions", Kind: "PodSecurityPolicy"}:                                ClusterScope,
		{Group: "extensions", Kind: "ReplicaSet"}:                                       NamespaceScope,
		{Group: "migration.k8s.io", Kind: "StorageState"}:                               ClusterScope,
		{Group: "migration.k8s.io", Kind: "StorageVersionMigration"}:                    ClusterScope,
		{Group: "networking.gke.io", Kind: "ManagedCertificate"}:                        NamespaceScope,
		{Group: "networking.k8s.io", Kind: "Ingress"}:                                   NamespaceScope,
		{Group: "networking.k8s.io", Kind: "NetworkPolicy"}:                             NamespaceScope,
		{Group: "node.k8s.io", Kind: "RuntimeClass"}:                                    ClusterScope,
		{Group: "nodemanagement.gke.io", Kind: "UpdateInfo"}:                            NamespaceScope,
		{Group: "policy", Kind: "PodDisruptionBudget"}:                                  NamespaceScope,
		{Group: "policy", Kind: "PodSecurityPolicy"}:                                    ClusterScope,
		{Group: "rbac.authorization.k8s.io", Kind: "ClusterRoleBinding"}:                ClusterScope,
		{Group: "rbac.authorization.k8s.io", Kind: "ClusterRole"}:                       ClusterScope,
		{Group: "rbac.authorization.k8s.io", Kind: "RoleBinding"}:                       NamespaceScope,
		{Group: "rbac.authorization.k8s.io", Kind: "Role"}:                              NamespaceScope,
		{Group: "scalingpolicy.kope.io", Kind: "ScalingPolicy"}:                         NamespaceScope,
		{Group: "scheduling.k8s.io", Kind: "PriorityClass"}:                             ClusterScope,
		{Group: "storage.k8s.io", Kind: "CSIDriver"}:                                    ClusterScope,
		{Group: "storage.k8s.io", Kind: "CSINode"}:                                      ClusterScope,
		{Group: "storage.k8s.io", Kind: "StorageClass"}:                                 ClusterScope,
		{Group: "storage.k8s.io", Kind: "VolumeAttachment"}:                             ClusterScope,
		{Group: "discovery.k8s.io", Kind: "EndpointSlice"}:                              NamespaceScope,
		{Group: "networking.gke.io", Kind: "FrontendConfig"}:                            NamespaceScope,
		{Group: "networking.gke.io", Kind: "ServiceNetworkEndpointGroup"}:               NamespaceScope,
		{Group: "networking.k8s.io", Kind: "IngressClass"}:                              ClusterScope,
		{Group: "snapshot.storage.k8s.io", Kind: "VolumeSnapshotClass"}:                 ClusterScope,
		{Group: "snapshot.storage.k8s.io", Kind: "VolumeSnapshotContent"}:               ClusterScope,
		{Group: "snapshot.storage.k8s.io", Kind: "VolumeSnapshot"}:                      NamespaceScope,
		{Group: "anthos.cloud.google.com", Kind: "Validator"}:                           NamespaceScope,
		{Group: "configmanagement.gke.io", Kind: "ClusterConfig"}:                       ClusterScope,
		{Group: "configmanagement.gke.io", Kind: "ClusterSelector"}:                     ClusterScope,
		{Group: "configmanagement.gke.io", Kind: "ConfigManagement"}:                    ClusterScope,
		{Group: "configmanagement.gke.io", Kind: "HierarchyConfig"}:                     ClusterScope,
		{Group: "configmanagement.gke.io", Kind: "NamespaceConfig"}:                     ClusterScope,
		{Group: "configmanagement.gke.io", Kind: "NamespaceSelector"}:                   ClusterScope,
		{Group: "configmanagement.gke.io", Kind: "Repo"}:                                ClusterScope,
		{Group: "configsync.gke.io", Kind: "Environment"}:                               NamespaceScope,
		{Group: "configsync.gke.io", Kind: "RepoSync"}:                                  NamespaceScope,
		{Group: "configsync.gke.io", Kind: "ResourceGroup"}:                             NamespaceScope,
		{Group: "configsync.gke.io", Kind: "RootSync"}:                                  NamespaceScope,
		{Group: "configmanagement.gke.io", Kind: "Sync"}:                                ClusterScope,
		{Group: "clusterregistry.k8s.io", Kind: "Cluster"}:                              ClusterScope,
		{Group: "kpt.dev", Kind: "Kptfile"}:                                             NamespaceScope,
	}}
}
