// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	monorepov1 "kpt.dev/configsync/pkg/api/monorepo/v1"
)

// FakeRepos implements RepoInterface
type FakeRepos struct {
	Fake *FakeMonorepoV1
}

var reposResource = schema.GroupVersionResource{Group: "monorepo", Version: "v1", Resource: "repos"}

var reposKind = schema.GroupVersionKind{Group: "monorepo", Version: "v1", Kind: "Repo"}

// Get takes name of the repo, and returns the corresponding repo object, and an error if there is any.
func (c *FakeRepos) Get(ctx context.Context, name string, options v1.GetOptions) (result *monorepov1.Repo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(reposResource, name), &monorepov1.Repo{})
	if obj == nil {
		return nil, err
	}
	return obj.(*monorepov1.Repo), err
}

// List takes label and field selectors, and returns the list of Repos that match those selectors.
func (c *FakeRepos) List(ctx context.Context, opts v1.ListOptions) (result *monorepov1.RepoList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(reposResource, reposKind, opts), &monorepov1.RepoList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &monorepov1.RepoList{ListMeta: obj.(*monorepov1.RepoList).ListMeta}
	for _, item := range obj.(*monorepov1.RepoList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested repos.
func (c *FakeRepos) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(reposResource, opts))
}

// Create takes the representation of a repo and creates it.  Returns the server's representation of the repo, and an error, if there is any.
func (c *FakeRepos) Create(ctx context.Context, repo *monorepov1.Repo, opts v1.CreateOptions) (result *monorepov1.Repo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(reposResource, repo), &monorepov1.Repo{})
	if obj == nil {
		return nil, err
	}
	return obj.(*monorepov1.Repo), err
}

// Update takes the representation of a repo and updates it. Returns the server's representation of the repo, and an error, if there is any.
func (c *FakeRepos) Update(ctx context.Context, repo *monorepov1.Repo, opts v1.UpdateOptions) (result *monorepov1.Repo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(reposResource, repo), &monorepov1.Repo{})
	if obj == nil {
		return nil, err
	}
	return obj.(*monorepov1.Repo), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeRepos) UpdateStatus(ctx context.Context, repo *monorepov1.Repo, opts v1.UpdateOptions) (*monorepov1.Repo, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(reposResource, "status", repo), &monorepov1.Repo{})
	if obj == nil {
		return nil, err
	}
	return obj.(*monorepov1.Repo), err
}

// Delete takes name of the repo and deletes it. Returns an error if one occurs.
func (c *FakeRepos) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(reposResource, name), &monorepov1.Repo{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRepos) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(reposResource, listOpts)

	_, err := c.Fake.Invokes(action, &monorepov1.RepoList{})
	return err
}

// Patch applies the patch and returns the patched repo.
func (c *FakeRepos) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *monorepov1.Repo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(reposResource, name, pt, data, subresources...), &monorepov1.Repo{})
	if obj == nil {
		return nil, err
	}
	return obj.(*monorepov1.Repo), err
}
