// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
	v1 "kpt.dev/configsync/clientgen/apis/typed/monorepo/v1"
)

type FakeMonorepoV1 struct {
	*testing.Fake
}

func (c *FakeMonorepoV1) ClusterConfigs() v1.ClusterConfigInterface {
	return &FakeClusterConfigs{c}
}

func (c *FakeMonorepoV1) NamespaceConfigs() v1.NamespaceConfigInterface {
	return &FakeNamespaceConfigs{c}
}

func (c *FakeMonorepoV1) Repos() v1.RepoInterface {
	return &FakeRepos{c}
}

func (c *FakeMonorepoV1) Syncs() v1.SyncInterface {
	return &FakeSyncs{c}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeMonorepoV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
