// Code generated by client-gen. DO NOT EDIT.

package v1

type ClusterConfigExpansion interface{}

type NamespaceConfigExpansion interface{}

type RepoExpansion interface{}

type SyncExpansion interface{}
