// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	rest "k8s.io/client-go/rest"
	"kpt.dev/configsync/clientgen/apis/scheme"
	v1 "kpt.dev/configsync/pkg/api/monorepo/v1"
)

type MonorepoV1Interface interface {
	RESTClient() rest.Interface
	ClusterConfigsGetter
	NamespaceConfigsGetter
	ReposGetter
	SyncsGetter
}

// MonorepoV1Client is used to interact with features provided by the monorepo group.
type MonorepoV1Client struct {
	restClient rest.Interface
}

func (c *MonorepoV1Client) ClusterConfigs() ClusterConfigInterface {
	return newClusterConfigs(c)
}

func (c *MonorepoV1Client) NamespaceConfigs() NamespaceConfigInterface {
	return newNamespaceConfigs(c)
}

func (c *MonorepoV1Client) Repos() RepoInterface {
	return newRepos(c)
}

func (c *MonorepoV1Client) Syncs() SyncInterface {
	return newSyncs(c)
}

// NewForConfig creates a new MonorepoV1Client for the given config.
func NewForConfig(c *rest.Config) (*MonorepoV1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &MonorepoV1Client{client}, nil
}

// NewForConfigOrDie creates a new MonorepoV1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *MonorepoV1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new MonorepoV1Client for the given RESTClient.
func New(c rest.Interface) *MonorepoV1Client {
	return &MonorepoV1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *MonorepoV1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
