// Code generated by lister-gen. DO NOT EDIT.

package v1

// ClusterConfigListerExpansion allows custom methods to be added to
// ClusterConfigLister.
type ClusterConfigListerExpansion interface{}

// NamespaceConfigListerExpansion allows custom methods to be added to
// NamespaceConfigLister.
type NamespaceConfigListerExpansion interface{}

// RepoListerExpansion allows custom methods to be added to
// RepoLister.
type RepoListerExpansion interface{}

// SyncListerExpansion allows custom methods to be added to
// SyncLister.
type SyncListerExpansion interface{}
