// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	rest "k8s.io/client-go/rest"
	"kpt.dev/configsync/clientgen/apis/scheme"
	v1 "kpt.dev/configsync/pkg/api/hub/v1"
)

type HubV1Interface interface {
	RESTClient() rest.Interface
}

// HubV1Client is used to interact with features provided by the hub.gke.io group.
type HubV1Client struct {
	restClient rest.Interface
}

// NewForConfig creates a new HubV1Client for the given config.
func NewForConfig(c *rest.Config) (*HubV1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &HubV1Client{client}, nil
}

// NewForConfigOrDie creates a new HubV1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *HubV1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new HubV1Client for the given RESTClient.
func New(c rest.Interface) *HubV1Client {
	return &HubV1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *HubV1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
