// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	scheme "kpt.dev/configsync/clientgen/apis/scheme"
	v1 "kpt.dev/configsync/pkg/api/configmanagement/v1"
)

// ClusterSelectorsGetter has a method to return a ClusterSelectorInterface.
// A group's client should implement this interface.
type ClusterSelectorsGetter interface {
	ClusterSelectors() ClusterSelectorInterface
}

// ClusterSelectorInterface has methods to work with ClusterSelector resources.
type ClusterSelectorInterface interface {
	Create(ctx context.Context, clusterSelector *v1.ClusterSelector, opts metav1.CreateOptions) (*v1.ClusterSelector, error)
	Update(ctx context.Context, clusterSelector *v1.ClusterSelector, opts metav1.UpdateOptions) (*v1.ClusterSelector, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.ClusterSelector, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.ClusterSelectorList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ClusterSelector, err error)
	ClusterSelectorExpansion
}

// clusterSelectors implements ClusterSelectorInterface
type clusterSelectors struct {
	client rest.Interface
}

// newClusterSelectors returns a ClusterSelectors
func newClusterSelectors(c *ConfigmanagementV1Client) *clusterSelectors {
	return &clusterSelectors{
		client: c.RESTClient(),
	}
}

// Get takes name of the clusterSelector, and returns the corresponding clusterSelector object, and an error if there is any.
func (c *clusterSelectors) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.ClusterSelector, err error) {
	result = &v1.ClusterSelector{}
	err = c.client.Get().
		Resource("clusterselectors").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ClusterSelectors that match those selectors.
func (c *clusterSelectors) List(ctx context.Context, opts metav1.ListOptions) (result *v1.ClusterSelectorList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.ClusterSelectorList{}
	err = c.client.Get().
		Resource("clusterselectors").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested clusterSelectors.
func (c *clusterSelectors) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("clusterselectors").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a clusterSelector and creates it.  Returns the server's representation of the clusterSelector, and an error, if there is any.
func (c *clusterSelectors) Create(ctx context.Context, clusterSelector *v1.ClusterSelector, opts metav1.CreateOptions) (result *v1.ClusterSelector, err error) {
	result = &v1.ClusterSelector{}
	err = c.client.Post().
		Resource("clusterselectors").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterSelector).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a clusterSelector and updates it. Returns the server's representation of the clusterSelector, and an error, if there is any.
func (c *clusterSelectors) Update(ctx context.Context, clusterSelector *v1.ClusterSelector, opts metav1.UpdateOptions) (result *v1.ClusterSelector, err error) {
	result = &v1.ClusterSelector{}
	err = c.client.Put().
		Resource("clusterselectors").
		Name(clusterSelector.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterSelector).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the clusterSelector and deletes it. Returns an error if one occurs.
func (c *clusterSelectors) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("clusterselectors").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *clusterSelectors) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("clusterselectors").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched clusterSelector.
func (c *clusterSelectors) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ClusterSelector, err error) {
	result = &v1.ClusterSelector{}
	err = c.client.Patch(pt).
		Resource("clusterselectors").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
