// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	rest "k8s.io/client-go/rest"
	"kpt.dev/configsync/clientgen/apis/scheme"
	v1 "kpt.dev/configsync/pkg/api/configmanagement/v1"
)

type ConfigmanagementV1Interface interface {
	RESTClient() rest.Interface
	ClusterConfigsGetter
	ClusterSelectorsGetter
	HierarchyConfigsGetter
	NamespaceConfigsGetter
	NamespaceSelectorsGetter
	ReposGetter
	SyncsGetter
}

// ConfigmanagementV1Client is used to interact with features provided by the configmanagement.gke.io group.
type ConfigmanagementV1Client struct {
	restClient rest.Interface
}

func (c *ConfigmanagementV1Client) ClusterConfigs() ClusterConfigInterface {
	return newClusterConfigs(c)
}

func (c *ConfigmanagementV1Client) ClusterSelectors() ClusterSelectorInterface {
	return newClusterSelectors(c)
}

func (c *ConfigmanagementV1Client) HierarchyConfigs() HierarchyConfigInterface {
	return newHierarchyConfigs(c)
}

func (c *ConfigmanagementV1Client) NamespaceConfigs() NamespaceConfigInterface {
	return newNamespaceConfigs(c)
}

func (c *ConfigmanagementV1Client) NamespaceSelectors() NamespaceSelectorInterface {
	return newNamespaceSelectors(c)
}

func (c *ConfigmanagementV1Client) Repos() RepoInterface {
	return newRepos(c)
}

func (c *ConfigmanagementV1Client) Syncs() SyncInterface {
	return newSyncs(c)
}

// NewForConfig creates a new ConfigmanagementV1Client for the given config.
func NewForConfig(c *rest.Config) (*ConfigmanagementV1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &ConfigmanagementV1Client{client}, nil
}

// NewForConfigOrDie creates a new ConfigmanagementV1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *ConfigmanagementV1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new ConfigmanagementV1Client for the given RESTClient.
func New(c rest.Interface) *ConfigmanagementV1Client {
	return &ConfigmanagementV1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *ConfigmanagementV1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
