// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	scheme "kpt.dev/configsync/clientgen/apis/scheme"
	v1 "kpt.dev/configsync/pkg/api/configmanagement/v1"
)

// ReposGetter has a method to return a RepoInterface.
// A group's client should implement this interface.
type ReposGetter interface {
	Repos() RepoInterface
}

// RepoInterface has methods to work with Repo resources.
type RepoInterface interface {
	Create(ctx context.Context, repo *v1.Repo, opts metav1.CreateOptions) (*v1.Repo, error)
	Update(ctx context.Context, repo *v1.Repo, opts metav1.UpdateOptions) (*v1.Repo, error)
	UpdateStatus(ctx context.Context, repo *v1.Repo, opts metav1.UpdateOptions) (*v1.Repo, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.Repo, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.RepoList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Repo, err error)
	RepoExpansion
}

// repos implements RepoInterface
type repos struct {
	client rest.Interface
}

// newRepos returns a Repos
func newRepos(c *ConfigmanagementV1Client) *repos {
	return &repos{
		client: c.RESTClient(),
	}
}

// Get takes name of the repo, and returns the corresponding repo object, and an error if there is any.
func (c *repos) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.Repo, err error) {
	result = &v1.Repo{}
	err = c.client.Get().
		Resource("repos").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Repos that match those selectors.
func (c *repos) List(ctx context.Context, opts metav1.ListOptions) (result *v1.RepoList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.RepoList{}
	err = c.client.Get().
		Resource("repos").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested repos.
func (c *repos) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("repos").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a repo and creates it.  Returns the server's representation of the repo, and an error, if there is any.
func (c *repos) Create(ctx context.Context, repo *v1.Repo, opts metav1.CreateOptions) (result *v1.Repo, err error) {
	result = &v1.Repo{}
	err = c.client.Post().
		Resource("repos").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(repo).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a repo and updates it. Returns the server's representation of the repo, and an error, if there is any.
func (c *repos) Update(ctx context.Context, repo *v1.Repo, opts metav1.UpdateOptions) (result *v1.Repo, err error) {
	result = &v1.Repo{}
	err = c.client.Put().
		Resource("repos").
		Name(repo.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(repo).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *repos) UpdateStatus(ctx context.Context, repo *v1.Repo, opts metav1.UpdateOptions) (result *v1.Repo, err error) {
	result = &v1.Repo{}
	err = c.client.Put().
		Resource("repos").
		Name(repo.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(repo).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the repo and deletes it. Returns an error if one occurs.
func (c *repos) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("repos").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *repos) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("repos").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched repo.
func (c *repos) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Repo, err error) {
	result = &v1.Repo{}
	err = c.client.Patch(pt).
		Resource("repos").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
