// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	scheme "kpt.dev/configsync/clientgen/apis/scheme"
	v1 "kpt.dev/configsync/pkg/api/configmanagement/v1"
)

// SyncsGetter has a method to return a SyncInterface.
// A group's client should implement this interface.
type SyncsGetter interface {
	Syncs() SyncInterface
}

// SyncInterface has methods to work with Sync resources.
type SyncInterface interface {
	Create(ctx context.Context, sync *v1.Sync, opts metav1.CreateOptions) (*v1.Sync, error)
	Update(ctx context.Context, sync *v1.Sync, opts metav1.UpdateOptions) (*v1.Sync, error)
	UpdateStatus(ctx context.Context, sync *v1.Sync, opts metav1.UpdateOptions) (*v1.Sync, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.Sync, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.SyncList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Sync, err error)
	SyncExpansion
}

// syncs implements SyncInterface
type syncs struct {
	client rest.Interface
}

// newSyncs returns a Syncs
func newSyncs(c *ConfigmanagementV1Client) *syncs {
	return &syncs{
		client: c.RESTClient(),
	}
}

// Get takes name of the sync, and returns the corresponding sync object, and an error if there is any.
func (c *syncs) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.Sync, err error) {
	result = &v1.Sync{}
	err = c.client.Get().
		Resource("syncs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Syncs that match those selectors.
func (c *syncs) List(ctx context.Context, opts metav1.ListOptions) (result *v1.SyncList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.SyncList{}
	err = c.client.Get().
		Resource("syncs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested syncs.
func (c *syncs) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("syncs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a sync and creates it.  Returns the server's representation of the sync, and an error, if there is any.
func (c *syncs) Create(ctx context.Context, sync *v1.Sync, opts metav1.CreateOptions) (result *v1.Sync, err error) {
	result = &v1.Sync{}
	err = c.client.Post().
		Resource("syncs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(sync).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a sync and updates it. Returns the server's representation of the sync, and an error, if there is any.
func (c *syncs) Update(ctx context.Context, sync *v1.Sync, opts metav1.UpdateOptions) (result *v1.Sync, err error) {
	result = &v1.Sync{}
	err = c.client.Put().
		Resource("syncs").
		Name(sync.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(sync).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *syncs) UpdateStatus(ctx context.Context, sync *v1.Sync, opts metav1.UpdateOptions) (result *v1.Sync, err error) {
	result = &v1.Sync{}
	err = c.client.Put().
		Resource("syncs").
		Name(sync.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(sync).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the sync and deletes it. Returns an error if one occurs.
func (c *syncs) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("syncs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *syncs) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("syncs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched sync.
func (c *syncs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Sync, err error) {
	result = &v1.Sync{}
	err = c.client.Patch(pt).
		Resource("syncs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
