// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	configmanagementv1 "kpt.dev/configsync/pkg/api/configmanagement/v1"
)

// FakeSyncs implements SyncInterface
type FakeSyncs struct {
	Fake *FakeConfigmanagementV1
}

var syncsResource = schema.GroupVersionResource{Group: "configmanagement.gke.io", Version: "v1", Resource: "syncs"}

var syncsKind = schema.GroupVersionKind{Group: "configmanagement.gke.io", Version: "v1", Kind: "Sync"}

// Get takes name of the sync, and returns the corresponding sync object, and an error if there is any.
func (c *FakeSyncs) Get(ctx context.Context, name string, options v1.GetOptions) (result *configmanagementv1.Sync, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(syncsResource, name), &configmanagementv1.Sync{})
	if obj == nil {
		return nil, err
	}
	return obj.(*configmanagementv1.Sync), err
}

// List takes label and field selectors, and returns the list of Syncs that match those selectors.
func (c *FakeSyncs) List(ctx context.Context, opts v1.ListOptions) (result *configmanagementv1.SyncList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(syncsResource, syncsKind, opts), &configmanagementv1.SyncList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &configmanagementv1.SyncList{ListMeta: obj.(*configmanagementv1.SyncList).ListMeta}
	for _, item := range obj.(*configmanagementv1.SyncList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested syncs.
func (c *FakeSyncs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(syncsResource, opts))
}

// Create takes the representation of a sync and creates it.  Returns the server's representation of the sync, and an error, if there is any.
func (c *FakeSyncs) Create(ctx context.Context, sync *configmanagementv1.Sync, opts v1.CreateOptions) (result *configmanagementv1.Sync, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(syncsResource, sync), &configmanagementv1.Sync{})
	if obj == nil {
		return nil, err
	}
	return obj.(*configmanagementv1.Sync), err
}

// Update takes the representation of a sync and updates it. Returns the server's representation of the sync, and an error, if there is any.
func (c *FakeSyncs) Update(ctx context.Context, sync *configmanagementv1.Sync, opts v1.UpdateOptions) (result *configmanagementv1.Sync, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(syncsResource, sync), &configmanagementv1.Sync{})
	if obj == nil {
		return nil, err
	}
	return obj.(*configmanagementv1.Sync), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSyncs) UpdateStatus(ctx context.Context, sync *configmanagementv1.Sync, opts v1.UpdateOptions) (*configmanagementv1.Sync, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(syncsResource, "status", sync), &configmanagementv1.Sync{})
	if obj == nil {
		return nil, err
	}
	return obj.(*configmanagementv1.Sync), err
}

// Delete takes name of the sync and deletes it. Returns an error if one occurs.
func (c *FakeSyncs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(syncsResource, name), &configmanagementv1.Sync{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSyncs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(syncsResource, listOpts)

	_, err := c.Fake.Invokes(action, &configmanagementv1.SyncList{})
	return err
}

// Patch applies the patch and returns the patched sync.
func (c *FakeSyncs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *configmanagementv1.Sync, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(syncsResource, name, pt, data, subresources...), &configmanagementv1.Sync{})
	if obj == nil {
		return nil, err
	}
	return obj.(*configmanagementv1.Sync), err
}
