// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	configmanagementv1 "kpt.dev/configsync/pkg/api/configmanagement/v1"
)

// FakeNamespaceSelectors implements NamespaceSelectorInterface
type FakeNamespaceSelectors struct {
	Fake *FakeConfigmanagementV1
}

var namespaceselectorsResource = schema.GroupVersionResource{Group: "configmanagement.gke.io", Version: "v1", Resource: "namespaceselectors"}

var namespaceselectorsKind = schema.GroupVersionKind{Group: "configmanagement.gke.io", Version: "v1", Kind: "NamespaceSelector"}

// Get takes name of the namespaceSelector, and returns the corresponding namespaceSelector object, and an error if there is any.
func (c *FakeNamespaceSelectors) Get(ctx context.Context, name string, options v1.GetOptions) (result *configmanagementv1.NamespaceSelector, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(namespaceselectorsResource, name), &configmanagementv1.NamespaceSelector{})
	if obj == nil {
		return nil, err
	}
	return obj.(*configmanagementv1.NamespaceSelector), err
}

// List takes label and field selectors, and returns the list of NamespaceSelectors that match those selectors.
func (c *FakeNamespaceSelectors) List(ctx context.Context, opts v1.ListOptions) (result *configmanagementv1.NamespaceSelectorList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(namespaceselectorsResource, namespaceselectorsKind, opts), &configmanagementv1.NamespaceSelectorList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &configmanagementv1.NamespaceSelectorList{ListMeta: obj.(*configmanagementv1.NamespaceSelectorList).ListMeta}
	for _, item := range obj.(*configmanagementv1.NamespaceSelectorList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested namespaceSelectors.
func (c *FakeNamespaceSelectors) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(namespaceselectorsResource, opts))
}

// Create takes the representation of a namespaceSelector and creates it.  Returns the server's representation of the namespaceSelector, and an error, if there is any.
func (c *FakeNamespaceSelectors) Create(ctx context.Context, namespaceSelector *configmanagementv1.NamespaceSelector, opts v1.CreateOptions) (result *configmanagementv1.NamespaceSelector, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(namespaceselectorsResource, namespaceSelector), &configmanagementv1.NamespaceSelector{})
	if obj == nil {
		return nil, err
	}
	return obj.(*configmanagementv1.NamespaceSelector), err
}

// Update takes the representation of a namespaceSelector and updates it. Returns the server's representation of the namespaceSelector, and an error, if there is any.
func (c *FakeNamespaceSelectors) Update(ctx context.Context, namespaceSelector *configmanagementv1.NamespaceSelector, opts v1.UpdateOptions) (result *configmanagementv1.NamespaceSelector, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(namespaceselectorsResource, namespaceSelector), &configmanagementv1.NamespaceSelector{})
	if obj == nil {
		return nil, err
	}
	return obj.(*configmanagementv1.NamespaceSelector), err
}

// Delete takes name of the namespaceSelector and deletes it. Returns an error if one occurs.
func (c *FakeNamespaceSelectors) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(namespaceselectorsResource, name), &configmanagementv1.NamespaceSelector{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNamespaceSelectors) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(namespaceselectorsResource, listOpts)

	_, err := c.Fake.Invokes(action, &configmanagementv1.NamespaceSelectorList{})
	return err
}

// Patch applies the patch and returns the patched namespaceSelector.
func (c *FakeNamespaceSelectors) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *configmanagementv1.NamespaceSelector, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(namespaceselectorsResource, name, pt, data, subresources...), &configmanagementv1.NamespaceSelector{})
	if obj == nil {
		return nil, err
	}
	return obj.(*configmanagementv1.NamespaceSelector), err
}
